//priority: 500

// ServerEvents.highPriorityData(event => {
//     global.lootbagType.forEach(type => {
//         global.lootbagRarity.forEach(rarity => {
//             event.addJson(`kubejs:data/lootbag/loot_tables/${type}/${rarity}`, {
//                 "type": "minecraft:chest",
//                 "pools": []
//             })
//         })
//     })
// })

function ItemOfBag(name, quantity, itemChance) {
    this.itemName = name;
    this.itemChance = itemChance || 5;
    this.quantity = quantity || 1;

    this.createItem = () => Item.of(`${this.quantity}x ${this.itemName}`).withChance(this.itemChance)
};

function Bag(lootPool, itemQuantity) {
    this.lootPool = lootPool.map(item => item.createItem());
    this.itemQuantity = itemQuantity || 1;
};
let food = {
    uncommon: new Bag([
        // name, quantity, itemChance
        new ItemOfBag("minecraft:mushroom_stew", 2, 40),
        new ItemOfBag("minecraft:carrot", 2, 70),
        new ItemOfBag("minecraft:potato", 2, 70),
        new ItemOfBag("minecraft:cookie", 4, 70),
        new ItemOfBag("expandeddelight:chocolate_cookie", 4, 20),
        new ItemOfBag("farmersdelight:kelp_roll_slice", 2, 10),
        new ItemOfBag("farmersdelight:melon_popsicle", 2, 20),
        new ItemOfBag("farmersdelight:sweet_berry_cookie", 2, 20),
        new ItemOfBag("farmersdelight:tomato_sauce", 1, 10),
        new ItemOfBag("farmersdelight:fried_egg", 2, 10),
        new ItemOfBag("minecraft:chicken", 4, 20),
        new ItemOfBag("minecraft:rabbit", 4, 20),
        new ItemOfBag("farmersdelight:cabbage", 2, 20),
        new ItemOfBag("minecraft:apple", 2, 20),
        new ItemOfBag("farmersdelight:milk_bottle", 2, 20),
        new ItemOfBag("farmersdelight:tomato", 2, 50),
        new ItemOfBag("farmersdelight:onion", 2, 50),
        new ItemOfBag("minecraft:pufferfish", 1, 10),
        new ItemOfBag("minecraft:salmon", 2, 40),
        new ItemOfBag("minecraft:cod", 2, 40),
        new ItemOfBag("minecraft:tropical_fish", 1, 20),
    ]),
    rare: new Bag([
        // name, quantity, itemChance
        new ItemOfBag("farmersdelight:honey_glazed_ham_block", 1, 5),
        new ItemOfBag("farmersdelight:shepherds_pie_block", 1, 5),
        new ItemOfBag("farmersdelight:rice_roll_medley_block", 1, 5),
        new ItemOfBag("farmersdelight:roast_chicken_block", 1, 5),
        new ItemOfBag("farmersdelight:barbecue_stick", 1, 50),
        new ItemOfBag("expandeddelight:glow_berry_sweet_roll", 2, 50),
        new ItemOfBag("farmersdelight:stuffed_potato", 1, 50),
        new ItemOfBag("farmersdelight:mixed_salad", 1, 40),
        new ItemOfBag("farmersdelight:glow_berry_custard", 1, 50),
        new ItemOfBag("expandeddelight:peanut_butter_honey_sandwich", 2, 30),
        new ItemOfBag("expandeddelight:grilled_cheese", 2, 30),
        new ItemOfBag("minecraft:cooked_cod", 8, 70),
        new ItemOfBag("expandeddelight:glow_berry_jelly_sandwich", 2, 20),
        new ItemOfBag("farmersdelight:stuffed_pumpkin_block", 1, 5),
        new ItemOfBag("minecraft:cooked_mutton", 8, 70),
        new ItemOfBag("minecraft:rabbit_stew", 4, 60),
        new ItemOfBag("minecraft:baked_potato", 8, 70),
        new ItemOfBag("minecraft:cooked_porkchop", 8, 60),
        new ItemOfBag("minecraft:cooked_salmon", 4, 40),
        new ItemOfBag("minecraft:golden_apple", 1, 10),
        new ItemOfBag("expandeddelight:sweet_berry_jelly_sandwich", 2, 20),
    ]),
    epic: new Bag([
        // name, quantity, itemChance
        new ItemOfBag("farmersdelight:pasta_with_meatballs", 2, 10),
        new ItemOfBag("expandeddelight:peperonata", 2, 10),
        new ItemOfBag("minecraft:enchanted_golden_apple", 1, 1),
        new ItemOfBag("minecraft:cake", 1, 30),
        new ItemOfBag("farmersdelight:melon_juice", 2, 60),
        new ItemOfBag("farmersdelight:chicken_sandwich", 2, 40),
        new ItemOfBag("farmersdelight:hamburger", 2, 40),
        new ItemOfBag("farmersdelight:mutton_wrap", 2, 40),
        new ItemOfBag("farmersdelight:smoked_ham", 2, 70),
        new ItemOfBag("farmersdelight:pasta_with_mutton_chop", 1, 60),
        new ItemOfBag("farmersdelight:mushroom_rice", 2, 20),
        new ItemOfBag("farmersdelight:roasted_mutton_chops", 1, 20),
        new ItemOfBag("farmersdelight:vegetable_noodles", 1, 20),
        new ItemOfBag("farmersdelight:steak_and_potatoes", 1, 20),
        new ItemOfBag("farmersdelight:ratatouille", 2, 60),
        new ItemOfBag("farmersdelight:squid_ink_pasta", 1, 20),
        new ItemOfBag("farmersdelight:roast_chicken", 1, 20),
    ]),
};

let mob = {
    uncommon: new Bag([
        // name, quantity, itemChance
        new ItemOfBag("minecraft:slime_ball", 4, 5),
        new ItemOfBag("minecraft:spider_eye", 5, 15),
        new ItemOfBag("minecraft:gunpowder", 8, 10),
        new ItemOfBag("minecraft:rotten_flesh", 8, 15),
        new ItemOfBag("minecraft:string", 8, 15),
        new ItemOfBag("minecraft:feather", 4, 10),
        new ItemOfBag("minecraft:ender_pearl", 1, 5),
        new ItemOfBag("minecraft:bone", 8, 15),
        new ItemOfBag("minecraft:leather", 4, 15),
        new ItemOfBag("minecraft:arrow", 8, 10),
        new ItemOfBag("minecraft:glow_ink_sac", 2, 5),
        new ItemOfBag("minecraft:ink_sac", 2, 5),
        new ItemOfBag("minecraft:rabbit_hide", 2, 5),
        new ItemOfBag("kubejs:moth_wings", 1, 15)
    ], 3),
    rare: new Bag([
        // name, quantity, itemChance
        new ItemOfBag("minecraft:gunpowder", 16, 10),
        new ItemOfBag("minecraft:string", 16, 15),
        new ItemOfBag("minecraft:ender_pearl", 2, 10),
        new ItemOfBag("minecraft:bone", 16, 15),
        new ItemOfBag("minecraft:leather", 8, 15),
        new ItemOfBag("minecraft:glow_ink_sac", 4, 5),
        new ItemOfBag("minecraft:ink_sac", 4, 5),
        new ItemOfBag("minecraft:rabbit_hide", 4, 5),
        new ItemOfBag("minecraft:prismarine_shard", 4, 15),
        new ItemOfBag("minecraft:prismarine_crystals", 4, 10),
        new ItemOfBag("minecraft:scute", 2, 5),
        new ItemOfBag("minecraft:magma_cream", 8, 10),
        new ItemOfBag("minecraft:blaze_rod", 4, 10),
        new ItemOfBag("kubejs:moth_wings", 2, 15),
        new ItemOfBag("minecraft:ghast_tear", 1, 5),
    ], 3),
    epic: new Bag([
        // name, quantity, itemChance
        new ItemOfBag("minecraft:gunpowder", 32, 10),
        new ItemOfBag("minecraft:string", 32, 15),
        new ItemOfBag("minecraft:ender_pearl", 8, 10),
        new ItemOfBag("minecraft:bone", 32, 15),
        new ItemOfBag("minecraft:rabbit_hide", 16, 5),
        new ItemOfBag("minecraft:prismarine_shard", 16, 15),
        new ItemOfBag("minecraft:prismarine_crystals", 16, 10),
        new ItemOfBag("minecraft:scute", 8, 5),
        new ItemOfBag("minecraft:leather", 16, 15),
        new ItemOfBag("minecraft:magma_cream", 16, 10),
        new ItemOfBag("minecraft:blaze_rod", 16, 10),
        new ItemOfBag("minecraft:ghast_tear", 4, 5),
        new ItemOfBag("minecraft:shulker_shell", 1, 1),
        new ItemOfBag("minecraft:skeleton_skull", 1, 10),
        new ItemOfBag("minecraft:wither_skeleton_skull", 1, 5),
        new ItemOfBag("minecraft:totem_of_undying", 1, 5),
        new ItemOfBag("minecraft:echo_shard", 1, 5),
        new ItemOfBag("kubejs:phantom_feather", 1, 1),
        new ItemOfBag("kubejs:zotzpyre_fang", 1, 1),
    ], 3),
};


let magic = {
    uncommon: new Bag([
        // name, quantity, itemChance
        new ItemOfBag('bewitchment:glowing_bramble', 1, 10),
        new ItemOfBag('bewitchment:fleeting_bramble', 1, 10),
        new ItemOfBag('bewitchment:thick_bramble', 1, 10),
        new ItemOfBag('bewitchment:scorched_bramble', 1, 10),
        new ItemOfBag('bewitchment:ender_bramble', 1, 10),
        new ItemOfBag('bewitchment:fruiting_bramble', 1, 10),
        new ItemOfBag('spirit:soul_powder', 4, 20),
        new ItemOfBag('bewitchment:heaven_extract', 1, 5),
        new ItemOfBag('bewitchment:demon_horn', 1, 5),
        new ItemOfBag('bewitchment:ectoplasm', 3, 5),
        new ItemOfBag('bewitchment:snake_tongue', 2, 5),
        new ItemOfBag('bewitchment:dragons_blood_resin', 1, 10),
        new ItemOfBag('spectrum:four_leaf_clover', 1, 1),
        new ItemOfBag('spectrum:vegetal', 3, 50),
        new ItemOfBag('spectrum:shimmerstone_gem', 2, 50),
        new ItemOfBag('spectrum:quitoxic_reeds', 2, 40),
        new ItemOfBag('spectrum:quitoxic_powder', 1, 40),
        new ItemOfBag('minecraft:amethyst_shard', 5, 50),
        new ItemOfBag('spectrum:citrine_shard', 5, 50),
        new ItemOfBag('spectrum:radiating_ender', 1, 5),
        new ItemOfBag('spectrum:topaz_shard', 5, 50),
        new ItemOfBag('spectrum:stardust', 1, 10),
        new ItemOfBag('spectrum:star_fragment', 1, 5),
        new ItemOfBag('bewitchment:earth_ichor', 1, 5),
        new ItemOfBag('bewitchment:fiery_serum', 1, 5),
        new ItemOfBag('bewitchment:aqua_cerate', 1, 5),
        new ItemOfBag('bewitchment:grim_elixir', 1, 5),
        new ItemOfBag('bewitchment:cleansing_balm', 1, 5),
        new ItemOfBag('bwplus:mutandis', 1, 20),
        new ItemOfBag('bwplus:soul', 1, 1),
        new ItemOfBag('mythicmetals:adamantite_ingot', 4, 20),
        new ItemOfBag('mythicmetals:aquarium_ingot', 1, 10),
        new ItemOfBag('mythicmetals:banglum_ingot', 4, 20),
        new ItemOfBag('mythicmetals:carmot_ingot', 4, 20),
        new ItemOfBag('mythicmetals:kyber_ingot', 2, 20),
        new ItemOfBag('mythicmetals:midas_gold_ingot', 1, 10),
        new ItemOfBag('mythicmetals:mythril_ingot', 4, 20),
        new ItemOfBag('mythicmetals:orichalcum_ingot', 4, 20),
        new ItemOfBag('mythicmetals:palladium_ingot', 2, 15),
        new ItemOfBag('mythicmetals:prometheum_ingot', 2, 20),
        new ItemOfBag('mythicmetals:quadrillum_ingot', 4, 20),
        new ItemOfBag('mythicmetals:runite_ingot', 4, 20),
        new ItemOfBag('mythicmetals:stormyx_ingot', 1, 10),
        new ItemOfBag('mythicmetals:morkite', 4, 40),
        new ItemOfBag('mythicmetals:starrite', 4, 40),
        new ItemOfBag('mythicmetals:unobtainium', 1, 2),
        new ItemOfBag('kubejs:raw_magical_steel', 1, 10),
        new ItemOfBag('fwaystones:abyss_watcher', 1, 10),
        new ItemOfBag('kubejs:leather_patch', 1, 20),
        new ItemOfBag('fwaystones:end_stone_brick_waystone', 1, 1),
        new ItemOfBag('kubejs:food_lootbag_uncommon', 1, 30),
        new ItemOfBag('kubejs:mob_lootbag_uncommon', 1, 10),
    ], 3),
    rare: new Bag([
        new ItemOfBag('mythicmetals:adamantite_ingot', 5, 20),
        new ItemOfBag('mythicmetals:aquarium_ingot', 2, 10),
        new ItemOfBag('mythicmetals:banglum_ingot', 5, 20),
        new ItemOfBag('mythicmetals:carmot_ingot', 5, 20),
        new ItemOfBag('mythicmetals:kyber_ingot', 4, 20),
        new ItemOfBag('mythicmetals:midas_gold_ingot', 2, 10),
        new ItemOfBag('mythicmetals:mythril_ingot', 5, 20),
        new ItemOfBag('mythicmetals:orichalcum_ingot', 5, 20),
        new ItemOfBag('mythicmetals:palladium_ingot', 5, 15),
        new ItemOfBag('mythicmetals:prometheum_ingot', 4, 20),
        new ItemOfBag('mythicmetals:quadrillum_ingot', 5, 20),
        new ItemOfBag('mythicmetals:runite_ingot', 5, 20),
        new ItemOfBag('mythicmetals:stormyx_ingot', 2, 10),
        new ItemOfBag('mythicmetals:morkite', 8, 40),
        new ItemOfBag('mythicmetals:starrite', 8, 40),
        new ItemOfBag('mythicmetals:unobtainium', 1, 1),
        new ItemOfBag('mythicmetals:durasteel_ingot', 1, 1),
        new ItemOfBag('mythicmetals:celestium_ingot', 1, 10),
        new ItemOfBag('mythicmetals:hallowed_ingot', 1, 10),
        new ItemOfBag('kubejs:raw_magical_steel', 1, 20),
        new ItemOfBag('spectrum:stratine_fragments', 2, 30),
        new ItemOfBag('spectrum:storm_stone', 2, 5),
        new ItemOfBag('spectrum:neolith', 1, 1),
        new ItemOfBag('spectrum:mermaids_gem', 2, 30),
        new ItemOfBag('spectrum:raw_azurite', 1, 1),
        new ItemOfBag('spectrum:midnight_chip', 1, 1),
        new ItemOfBag('bewitchment:dragons_blood_resin', 1, 40),
        new ItemOfBag('bewitchment:ectoplasm', 4, 50),
        new ItemOfBag('bewitchment:snake_tongue', 4, 50),
        new ItemOfBag('bewitchment:demon_horn', 4, 50),
        new ItemOfBag('spectrum:shimmerstone_gem', 4, 70),
        new ItemOfBag('spectrum:vegetal', 5, 70),
        new ItemOfBag('spectrum:topaz_shard', 8, 70),
        new ItemOfBag('spectrum:citrine_shard', 8, 70),
        new ItemOfBag('spectrum:radiating_ender', 1, 5),
        new ItemOfBag('minecraft:amethyst_shard', 8, 70),
        new ItemOfBag('spectrum:star_fragment', 1, 20),
        new ItemOfBag('spectrum:stardust', 2, 60),
        new ItemOfBag('bwplus:soul', 1, 20),
        new ItemOfBag('spirit:soul_powder', 8, 40),
        new ItemOfBag('bwplus:mutandis', 1, 80),
        new ItemOfBag('bewitchment:heaven_extract', 1, 40),
        new ItemOfBag('bewitchment:cleansing_balm', 1, 40),
        new ItemOfBag('bewitchment:grim_elixir', 1, 40),
        new ItemOfBag('bewitchment:aqua_cerate', 1, 40),
        new ItemOfBag('bewitchment:fiery_serum', 1, 40),
        new ItemOfBag('bewitchment:earth_ichor', 1, 40),
        new ItemOfBag('bewitchment:demon_heart', 1, 1),
        new ItemOfBag('spectrum:upgrade_speed', 1, 5),
        new ItemOfBag('spectrum:upgrade_speed2', 1, 1),
        new ItemOfBag('spectrum:onyx_shard', 1, 1),
        new ItemOfBag('fwaystones:abyss_watcher', 1, 10),
        new ItemOfBag('kubejs:leather_patch', 1, 20),
        new ItemOfBag('adventurez:stone_golem_heart', 1, 5),
        new ItemOfBag('fwaystones:end_stone_brick_waystone', 1, 5),
        new ItemOfBag('minecraft:nether_star', 1, 5),
        new ItemOfBag('kubejs:food_lootbag_rare', 1, 20),
        new ItemOfBag('kubejs:mob_lootbag_rare', 1, 20),
    ], 3),
    epic: new Bag([
        new ItemOfBag('mythicmetals:adamantite_ingot', 7, 20),
        new ItemOfBag('mythicmetals:aquarium_ingot', 4, 10),
        new ItemOfBag('mythicmetals:banglum_ingot', 7, 20),
        new ItemOfBag('mythicmetals:carmot_ingot', 7, 20),
        new ItemOfBag('mythicmetals:kyber_ingot', 5, 20),
        new ItemOfBag('mythicmetals:midas_gold_ingot', 4, 10),
        new ItemOfBag('mythicmetals:mythril_ingot', 7, 20),
        new ItemOfBag('mythicmetals:orichalcum_ingot', 7, 20),
        new ItemOfBag('mythicmetals:palladium_ingot', 7, 15),
        new ItemOfBag('mythicmetals:prometheum_ingot', 6, 20),
        new ItemOfBag('mythicmetals:quadrillum_ingot', 7, 20),
        new ItemOfBag('mythicmetals:runite_ingot', 7, 20),
        new ItemOfBag('mythicmetals:stormyx_ingot', 4, 10),
        new ItemOfBag('mythicmetals:morkite', 16, 40),
        new ItemOfBag('mythicmetals:starrite', 16, 40),
        new ItemOfBag('mythicmetals:unobtainium', 2, 1),
        new ItemOfBag('mythicmetals:durasteel_ingot', 2, 1),
        new ItemOfBag('mythicmetals:celestium_ingot', 2, 10),
        new ItemOfBag('mythicmetals:hallowed_ingot', 2, 10),
        new ItemOfBag('mythicmetals:metallurgium_ingot', 1, 1),
        new ItemOfBag('spectrum:citrine_shard', 16, 70),
        new ItemOfBag('spectrum:neolith', 4, 20),
        new ItemOfBag('spectrum:storm_stone', 2, 10),
        new ItemOfBag('spectrum:stratine_fragments', 8, 30),
        new ItemOfBag('spectrum:mermaids_gem', 4, 50),
        new ItemOfBag('spectrum:midnight_chip', 1, 10),
        new ItemOfBag('spectrum:resonance_shard', 1, 5),
        new ItemOfBag('spectrum:bedrock_dust', 1, 20),
        new ItemOfBag('spectrum:bismuth_crystal', 1, 1),
        new ItemOfBag('spectrum:bismuth_flake', 1, 5),
        new ItemOfBag('spectrum:onyx_shard', 1, 30),
        new ItemOfBag('minecraft:amethyst_shard', 16, 50),
        new ItemOfBag('spectrum:shimmerstone_gem', 16, 60),
        new ItemOfBag('spectrum:radiating_ender', 4, 30),
        new ItemOfBag('spectrum:refined_azurite', 1, 40),
        new ItemOfBag('spectrum:raw_azurite', 1, 60),
        new ItemOfBag('spectrum:dragonbone_chunk', 1, 1),
        new ItemOfBag('spectrum:refined_bloodstone', 1, 1),
        new ItemOfBag('spectrum:raw_bloodstone', 1, 5),
        new ItemOfBag('spectrum:effulgent_feather', 1, 5),
        new ItemOfBag('spectrum:paltaeria_gem', 1, 20),
        new ItemOfBag('spectrum:refined_malachite', 1, 5),
        new ItemOfBag('spectrum:raw_malachite', 1, 20),
        new ItemOfBag('spectrum:mysterious_locket', 1, 1),
        new ItemOfBag('spectrum:moonstone_core', 1, 1),
        new ItemOfBag('kubejs:raw_magical_steel', 8, 70),
        new ItemOfBag('spectrum:paltaeria_fragments', 4, 40),
        new ItemOfBag('spectrum:blood_orchid_petal', 1, 5),
        new ItemOfBag('bwplus:soul', 4, 70),
        new ItemOfBag('bewitchment:demon_heart', 1, 10),
        new ItemOfBag('bewitchment:snake_tongue', 4, 50),
        new ItemOfBag('bewitchment:ectoplasm', 4, 50),
        new ItemOfBag('bewitchment:demon_horn', 2, 50),
        new ItemOfBag('spectrum:vegetal', 12, 60),
        new ItemOfBag('bwplus:mutandis', 4, 50),
        new ItemOfBag('spectrum:topaz_shard', 16, 60),
        new ItemOfBag('spectrum:upgrade_speed3', 1, 1),
        new ItemOfBag('botania:rune_air', 1, 5),
        new ItemOfBag('botania:mana_diamond', 1, 5),
        new ItemOfBag('botania:mana_pearl', 1, 15),
        new ItemOfBag('botania:manasteel_ingot', 1, 20),
        new ItemOfBag('botania:mana_spreader', 1, 5),
        new ItemOfBag('botania:mana_pool', 1, 10),
        new ItemOfBag('botania:mana_pylon', 1, 5),
        new ItemOfBag('botania:mana_cookie', 4, 70),
        new ItemOfBag('botania:rune_earth', 1, 5),
        new ItemOfBag('botania:rune_water', 1, 5),
        new ItemOfBag('botania:rune_fire', 1, 5),
        new ItemOfBag('fwaystones:abyss_watcher', 1, 10),
        new ItemOfBag('kubejs:leather_patch', 1, 20),
        new ItemOfBag('adventurez:stone_golem_heart', 1, 10),
        new ItemOfBag('fwaystones:end_stone_brick_waystone', 1, 5),
        new ItemOfBag('kubejs:food_lootbag_epic', 1, 10),
        new ItemOfBag('kubejs:mob_lootbag_epic', 1, 10),
    ], 3),
};

let early = {
    uncommon: new Bag([
        new ItemOfBag('minecraft:lapis_lazuli', 8, 70),
        new ItemOfBag('minecraft:clay_ball', 8, 70),
        new ItemOfBag('minecraft:redstone', 16, 70),
        new ItemOfBag('minecraft:name_tag', 1, 20),
        new ItemOfBag('minecraft:coal', 16, 70),
        new ItemOfBag('minecraft:gunpowder', 4, 50),
        new ItemOfBag('minecraft:leather', 4, 40),
        new ItemOfBag('minecraft:string', 4, 50),
        new ItemOfBag('minecraft:charcoal', 16, 70),
        new ItemOfBag('minecraft:raw_iron', 16, 70),
        new ItemOfBag('minecraft:bone', 2, 40),
        new ItemOfBag('minecraft:bamboo', 1, 60),
        new ItemOfBag('minecraft:purple_bed', 1, 10),
        new ItemOfBag('minecraft:campfire', 1, 30),
        new ItemOfBag('minecraft:barrel', 1, 40),
        new ItemOfBag('minecraft:smoker', 1, 40),
        new ItemOfBag('minecraft:blast_furnace', 1, 40),
        new ItemOfBag('minecraft:furnace', 1, 30),
        new ItemOfBag('minecraft:birch_sapling', 1, 50),
        new ItemOfBag('minecraft:raw_copper', 32, 70),
        new ItemOfBag('minecraft:raw_gold', 16, 70),
        new ItemOfBag('minecraft:oak_sapling', 1, 50),
        new ItemOfBag('minecraft:melon_seeds', 1, 50),
        new ItemOfBag('modern_industrialization:steam_mining_drill', 1, 1),
        new ItemOfBag('minecraft:bundle', 1, 10),
        new ItemOfBag('minecraft:spruce_sapling', 1, 50),
        new ItemOfBag('minecraft:chest', 1, 40),
        new ItemOfBag('modern_industrialization:iron_hammer', 1, 5),
        new ItemOfBag('modern_industrialization:forge_hammer', 1, 5),
        new ItemOfBag('minecraft:oak_log', 12, 70),
        new ItemOfBag('modern_industrialization:raw_tin', 8, 70),
        new ItemOfBag('minecraft:acacia_sapling', 1, 50),
        new ItemOfBag('minecraft:jungle_sapling', 1, 50),
        new ItemOfBag('minecraft:quartz', 2, 30),
        new ItemOfBag('minecraft:amethyst_shard', 4, 20),
        new ItemOfBag('minecraft:slime_ball', 2, 70),
        new ItemOfBag('minecraft:sugar_cane', 1, 40),
        new ItemOfBag('minecraft:fishing_rod', 1, 10),
        new ItemOfBag('minecraft:spyglass', 1, 10),
        new ItemOfBag('minecraft:clock', 1, 20),
        new ItemOfBag('minecraft:shears', 1, 10),
        new ItemOfBag('minecraft:lead', 1, 20),
        new ItemOfBag('minecraft:dark_oak_sapling', 2, 50),
        new ItemOfBag('minecraft:pumpkin_seeds', 1, 50),
    ], 3),
    rare: new Bag([
        new ItemOfBag('minecraft:gunpowder', 8, 80),
        new ItemOfBag('minecraft:diamond_hoe', 1, 10),
        new ItemOfBag('minecraft:diamond_axe', 1, 10),
        new ItemOfBag('minecraft:diamond_pickaxe', 1, 10),
        new ItemOfBag('minecraft:diamond_shovel', 1, 10),
        new ItemOfBag('minecraft:raw_gold', 16, 50),
        new ItemOfBag('minecraft:raw_copper', 64, 50),
        new ItemOfBag('minecraft:raw_iron', 16, 50),
        new ItemOfBag('minecraft:redstone', 16, 50),
        new ItemOfBag('modern_industrialization:raw_tin', 16, 50),
        new ItemOfBag('modern_industrialization:steel_ingot', 2, 20),
        new ItemOfBag('modern_industrialization:fire_clay_bricks', 2, 20),
        new ItemOfBag('modern_industrialization:bronze_ingot', 4, 30),
        new ItemOfBag('modern_industrialization:bronze_water_pump', 1, 5),
        new ItemOfBag('modern_industrialization:bronze_boiler', 1, 5),
        new ItemOfBag('modern_industrialization:bronze_mixer', 1, 5),
        new ItemOfBag('modern_industrialization:bronze_macerator', 1, 5),
        new ItemOfBag('modern_industrialization:bronze_furnace', 1, 5),
        new ItemOfBag('modern_industrialization:bronze_cutting_machine', 1, 5),
        new ItemOfBag('modern_industrialization:bronze_compressor', 1, 5),
        new ItemOfBag('modern_industrialization:steel_barrel', 1, 1),
        new ItemOfBag('modern_industrialization:bronze_barrel', 1, 10),
        new ItemOfBag('modern_industrialization:steel_tank', 1, 1),
        new ItemOfBag('modern_industrialization:bronze_tank', 1, 10),
        new ItemOfBag('modern_industrialization:steam_mining_drill', 1, 1),
        new ItemOfBag('modern_industrialization:steel_upgrade', 1, 1),
        new ItemOfBag('modern_industrialization:diamond_hammer', 1, 10),
        new ItemOfBag('modern_industrialization:steel_hammer', 1, 10),
        new ItemOfBag('autoworkstations:gold_auto_crafting_table', 1, 20),
        new ItemOfBag('autoworkstations:iron_auto_crafting_table', 1, 20),
        new ItemOfBag('minecraft:bone', 8, 80),
        new ItemOfBag('minecraft:bundle', 1, 10),
        new ItemOfBag('minecraft:slime_ball', 4, 80),
        new ItemOfBag('extended_drawers:t1_upgrade', 1, 10),
        new ItemOfBag('extended_drawers:t2_upgrade', 1, 5),
    ], 3),
    epic: new Bag([
        new ItemOfBag('botania:cosmetic_thinking_hand', 1, 5),
        new ItemOfBag('botania:cosmetic_tiny_potato_mask', 1, 5),
        new ItemOfBag('botania:cosmetic_devil_horns', 1, 5),
        new ItemOfBag('botania:cosmetic_red_ribbons', 1, 5),
        new ItemOfBag('botania:cosmetic_devil_tail', 1, 5),
        new ItemOfBag('botania:cosmetic_googly_eyes', 1, 5),
        new ItemOfBag('botania:cosmetic_groucho_glasses', 1, 5),
        new ItemOfBag('botania:cosmetic_black_tie', 1, 5),
        new ItemOfBag('botania:cosmetic_black_bowtie', 1, 5),
        new ItemOfBag('kibe:purple_glider', 1, 1),
        new ItemOfBag('modern_industrialization:tin_cable', 4, 40),
        new ItemOfBag('modern_industrialization:steam_quarry', 1, 1),
        new ItemOfBag('modern_industrialization:steel_cutting_machine', 1, 5),
        new ItemOfBag('modern_industrialization:steel_macerator', 1, 5),
        new ItemOfBag('modern_industrialization:steel_furnace', 1, 5),
        new ItemOfBag('modern_industrialization:steel_mixer', 1, 5),
        new ItemOfBag('modern_industrialization:steel_packer', 1, 5),
        new ItemOfBag('modern_industrialization:large_tank', 1, 5),
        new ItemOfBag('modern_industrialization:large_tank_hatch', 1, 5),
        new ItemOfBag('modern_industrialization:bronze_ingot', 2, 60),
        new ItemOfBag('modern_industrialization:steel_ingot', 2, 60),
        new ItemOfBag('modern_industrialization:steam_blast_furnace', 1, 5),
        new ItemOfBag('modern_industrialization:steel_machine_casing', 1, 5),
        new ItemOfBag('modern_industrialization:steel_machine_casing_pipe', 1, 5),
        new ItemOfBag('minecraft:elytra', 1, 1),
        new ItemOfBag('minecraft:raw_gold', 64, 80),
        new ItemOfBag('minecraft:raw_copper', 64, 80),
        new ItemOfBag('modern_industrialization:steel_tank', 1, 10),
        new ItemOfBag('minecraft:gunpowder', 12, 50),
        new ItemOfBag('minecraft:slime_ball', 8, 80),
        new ItemOfBag('minecraft:bundle', 1, 20),
        new ItemOfBag('modern_industrialization:bronze_barrel', 1, 20),
        new ItemOfBag('modern_industrialization:steel_barrel', 1, 10),
        new ItemOfBag('modern_industrialization:steel_unpacker', 1, 5),
        new ItemOfBag('modern_industrialization:steel_boiler', 1, 5),
        new ItemOfBag('autoworkstations:gold_auto_crafting_table', 1, 40),
        new ItemOfBag('minecraft:bone', 12, 80),
        new ItemOfBag('minecraft:redstone', 64, 80),
        new ItemOfBag('modern_industrialization:steel_compressor', 1, 5),
        new ItemOfBag('modern_industrialization:steel_upgrade', 1, 5),
        new ItemOfBag('modern_industrialization:steel_wiremill', 1, 5),
        new ItemOfBag('modern_industrialization:basic_machine_hull', 1, 15),
        new ItemOfBag('autoworkstations:iron_auto_crafting_table', 1, 40),
        new ItemOfBag('modern_industrialization:aluminum_tank', 1, 1),
        new ItemOfBag('modern_industrialization:aluminum_barrel', 1, 1),
        new ItemOfBag('modern_industrialization:steel_water_pump', 1, 5),
        new ItemOfBag('minecraft:raw_iron', 64, 80),
        new ItemOfBag('modern_industrialization:raw_tin', 64, 80),
        new ItemOfBag('extended_drawers:t1_upgrade', 1, 30),
        new ItemOfBag('extended_drawers:t2_upgrade', 1, 20),
    ], 3),
};

let mid = {
    uncommon: new Bag([
        new ItemOfBag('modern_industrialization:bronze_barrel', 1, 1),
        new ItemOfBag('modern_industrialization:steel_barrel', 1, 1),
        new ItemOfBag('modern_industrialization:aluminum_barrel', 2, 30),
        new ItemOfBag('modern_industrialization:aluminum_tank', 2, 30),
        new ItemOfBag('modern_industrialization:steel_tank', 4, 20),
        new ItemOfBag('modern_industrialization:large_tank', 1, 15),
        new ItemOfBag('modern_industrialization:large_tank_hatch', 2, 20),
        
        new ItemOfBag('modern_industrialization:steel_ingot', 16, 40),
        new ItemOfBag('modern_industrialization:bronze_ingot', 32, 60),
        new ItemOfBag('modern_industrialization:pump', 2, 40),
        new ItemOfBag('modern_industrialization:motor', 2, 40),
        new ItemOfBag('modern_industrialization:analog_circuit', 1, 30),
        new ItemOfBag('modern_industrialization:inductor', 2, 40),
        new ItemOfBag('modern_industrialization:capacitor', 8, 30),
        new ItemOfBag('modern_industrialization:basic_machine_hull', 3, 30),
        new ItemOfBag('modern_industrialization:steel_upgrade', 4, 40),
        new ItemOfBag('modern_industrialization:resistor', 4, 30),
        new ItemOfBag('modern_industrialization:conveyor', 4, 20),
        new ItemOfBag('modern_industrialization:robot_arm', 4, 15),
        new ItemOfBag('modern_industrialization:piston', 4, 30),
        new ItemOfBag('modern_industrialization:steel_machine_casing', 8, 20),
        new ItemOfBag('modern_industrialization:steel_machine_casing_pipe', 8, 20),

        new ItemOfBag('modern_industrialization:trash_can', 1, 20),
        new ItemOfBag('modern_industrialization:steel_cutting_machine', 1, 70),
        new ItemOfBag('autoworkstations:iron_auto_crafting_table', 1, 80),
        new ItemOfBag('autoworkstations:gold_auto_crafting_table', 1, 40),
        new ItemOfBag('modern_industrialization:steel_boiler', 1, 60),
        new ItemOfBag('modern_industrialization:steel_wiremill', 1, 50),
        new ItemOfBag('modern_industrialization:steel_packer', 1, 50),
        new ItemOfBag('modern_industrialization:steel_compressor', 1, 80),
        new ItemOfBag('modern_industrialization:steel_water_pump', 1, 80),
        new ItemOfBag('modern_industrialization:steel_macerator', 1, 80),
        new ItemOfBag('modern_industrialization:steel_furnace', 1, 80),
        new ItemOfBag('modern_industrialization:steel_mixer', 1, 80),
        new ItemOfBag('modern_industrialization:steel_unpacker', 1, 80),
        new ItemOfBag('modern_industrialization:large_steam_boiler', 1, 15),
        new ItemOfBag('modern_industrialization:steam_quarry', 1, 15),

        new ItemOfBag('modern_industrialization:tin_cable', 16, 60),
        new ItemOfBag('modern_industrialization:fluid_pipe', 16, 40),
        new ItemOfBag('modern_industrialization:item_pipe', 16, 20),

        new ItemOfBag('minecraft:bundle', 1, 10),
    ]),
    rare: new Bag([
        new ItemOfBag('modern_industrialization:aluminum_barrel', 2, 60),
        new ItemOfBag('modern_industrialization:aluminum_tank', 2, 60),

        new ItemOfBag('modern_industrialization:lv_steam_turbine', 1, 30),
        new ItemOfBag('modern_industrialization:mv_steam_turbine', 1, 15),
        new ItemOfBag('modern_industrialization:lv_energy_output_hatch', 2, 30),
        new ItemOfBag('modern_industrialization:lv_energy_input_hatch', 2, 30),
        new ItemOfBag('modern_industrialization:large_steam_boiler', 1, 10),
        new ItemOfBag('modern_industrialization:advanced_large_steam_boiler', 1, 5),

        new ItemOfBag('modern_industrialization:electric_unpacker', 2, 50),
        new ItemOfBag('modern_industrialization:electric_wiremill', 2, 50),
        new ItemOfBag('modern_industrialization:electric_mixer', 2, 50),
        new ItemOfBag('modern_industrialization:electric_blast_furnace', 2, 50),
        new ItemOfBag('modern_industrialization:electric_fluid_extractor', 2, 50),
        new ItemOfBag('modern_industrialization:electric_macerator', 2, 50),
        new ItemOfBag('modern_industrialization:electric_furnace', 2, 50),
        new ItemOfBag('modern_industrialization:electric_packer', 2, 50),
        new ItemOfBag('modern_industrialization:electric_compressor', 2, 50),
        new ItemOfBag('modern_industrialization:electric_cutting_machine', 2, 1),

        new ItemOfBag('modern_industrialization:polarizer', 2, 25),
        new ItemOfBag('modern_industrialization:distillery', 2, 25),
        new ItemOfBag('modern_industrialization:bottler', 2, 25),
        new ItemOfBag('modern_industrialization:centrifuge', 1, 25),
        new ItemOfBag('modern_industrialization:chemical_reactor', 1, 25),
        new ItemOfBag('modern_industrialization:electrolyzer', 1, 25),
        new ItemOfBag('modern_industrialization:assembler', 1, 25),

        new ItemOfBag('modern_industrialization:piston', 4, 30),
        new ItemOfBag('modern_industrialization:pump', 4, 30),
        new ItemOfBag('modern_industrialization:robot_arm', 6, 30),
        new ItemOfBag('modern_industrialization:electronic_circuit', 4, 30),
        new ItemOfBag('modern_industrialization:conveyor', 6, 30),
        new ItemOfBag('modern_industrialization:motor', 4, 30),
        new ItemOfBag('modern_industrialization:analog_circuit', 6, 30),
        new ItemOfBag('modern_industrialization:large_pump', 2, 30),
        new ItemOfBag('modern_industrialization:large_motor', 2, 30),
        new ItemOfBag('modern_industrialization:resistor', 12, 30),
        new ItemOfBag('modern_industrialization:inductor', 12, 30),
        new ItemOfBag('modern_industrialization:capacitor', 12, 30),

        new ItemOfBag('modern_industrialization:fluid_pipe', 16, 60),
        new ItemOfBag('modern_industrialization:item_pipe', 16, 60),

        new ItemOfBag('modern_industrialization:trash_can', 2, 30),

        new ItemOfBag('modern_industrialization:frostproof_machine_casing', 8, 25),
    ]),
    epic: new Bag([
        new ItemOfBag('botania:cosmetic_black_bowtie', 1, 1),
        new ItemOfBag('botania:cosmetic_groucho_glasses', 1, 1),
        new ItemOfBag('botania:cosmetic_googly_eyes', 1, 1),
        new ItemOfBag('botania:cosmetic_devil_tail', 1, 1),
        new ItemOfBag('botania:cosmetic_red_ribbons', 1, 1),
        new ItemOfBag('botania:cosmetic_devil_horns', 1, 1),
        new ItemOfBag('botania:cosmetic_tiny_potato_mask', 1, 1),
        new ItemOfBag('botania:cosmetic_thinking_hand', 1, 1),
        new ItemOfBag('botania:cosmetic_black_tie', 1, 1),

        new ItemOfBag('modern_industrialization:pump', 12, 60),
        new ItemOfBag('modern_industrialization:robot_arm', 8, 50),
        new ItemOfBag('modern_industrialization:digital_circuit', 2, 15),
        new ItemOfBag('modern_industrialization:or_gate', 4, 45),
        new ItemOfBag('modern_industrialization:not_gate', 4, 45),
        new ItemOfBag('modern_industrialization:and_gate', 4, 45),
        new ItemOfBag('modern_industrialization:digital_circuit_board', 2, 25),
        new ItemOfBag('modern_industrialization:large_pump', 6, 30),
        new ItemOfBag('modern_industrialization:electronic_circuit', 6, 50),
        new ItemOfBag('modern_industrialization:large_motor', 4, 30),

        new ItemOfBag('modern_industrialization:stainless_steel_ingot', 16, 80),

        new ItemOfBag('modern_industrialization:turbo_machine_hull', 2, 35),
        new ItemOfBag('modern_industrialization:centrifuge', 1, 45),
        new ItemOfBag('modern_industrialization:electric_quarry', 1, 50),
        
        new ItemOfBag('modern_industrialization:basic_upgrade', 4, 60),
        new ItemOfBag('modern_industrialization:advanced_upgrade', 4, 20),

        new ItemOfBag('modern_industrialization:stainless_steel_barrel', 1, 30),
        new ItemOfBag('modern_industrialization:stainless_steel_tank', 1, 30),
        new ItemOfBag('modern_industrialization:stainless_steel_drill', 8, 15),

        new ItemOfBag('modern_industrialization:mv_steam_turbine', 2, 35),
    ]),
};

let late = {
    uncommon: new Bag([
        new ItemOfBag('modern_industrialization:digital_circuit', 2, 15),
        new ItemOfBag('modern_industrialization:large_pump', 6, 30),
        new ItemOfBag('modern_industrialization:large_motor', 4, 30),
        new ItemOfBag('modern_industrialization:processing_unit_board', 2, 25),
        new ItemOfBag('modern_industrialization:processing_unit', 2, 25),
        new ItemOfBag('modern_industrialization:random_access_memory',1,20),
        new ItemOfBag('modern_industrialization:memory_management_unit',1,20),
        new ItemOfBag('modern_industrialization:arithmetic_logic_unit',1,20),
        new ItemOfBag('modern_industrialization:heat_exchanger',1,20),
        new ItemOfBag('modern_industrialization:turbo_machine_hull', 2, 35),

        new ItemOfBag('modern_industrialization:titanium_ingot', 16, 80),
        new ItemOfBag('modern_industrialization:uranium_fuel_rod', 4, 80),

        new ItemOfBag('modern_industrialization:electric_greenhouse',1,40),
        new ItemOfBag('modern_industrialization:solid_titanium_machine_casing', 2, 35),
        new ItemOfBag('modern_industrialization:blast_alloy_smelter',1,25),
        
        new ItemOfBag('modern_industrialization:advanced_upgrade', 4, 20),
        new ItemOfBag('modern_industrialization:turbo_upgrade', 4, 20),

        new ItemOfBag('modern_industrialization:titanium_barrel', 1, 30),
        new ItemOfBag('modern_industrialization:titanium_tank', 1, 30),
        new ItemOfBag('modern_industrialization:titanium_drill', 8, 15),

        new ItemOfBag('modern_industrialization:annealed_copper_cable',16,40),
        new ItemOfBag('modern_industrialization:hv_steam_turbine', 2, 35),
    ]),
    rare: new Bag([
        new ItemOfBag('modern_industrialization:large_pump', 6, 30),
        new ItemOfBag('modern_industrialization:large_motor', 4, 30),
        new ItemOfBag('modern_industrialization:large_advanced_pump', 6, 30),
        new ItemOfBag('modern_industrialization:large_advanced_motor', 4, 30),
        new ItemOfBag('modern_industrialization:processing_unit_board', 2, 25),
        new ItemOfBag('modern_industrialization:processing_unit', 2, 25),
        new ItemOfBag('modern_industrialization:random_access_memory',1,20),
        new ItemOfBag('modern_industrialization:memory_management_unit',1,20),
        new ItemOfBag('modern_industrialization:arithmetic_logic_unit',1,20),
        new ItemOfBag('modern_industrialization:heat_exchanger',1,20),
        new ItemOfBag('modern_industrialization:highly_advanced_machine_hull',1,20),

        new ItemOfBag('modern_industrialization:titanium_ingot', 16, 80),
        new ItemOfBag('modern_industrialization:indium_phosphide_plate', 16, 80),
        new ItemOfBag('modern_industrialization:uranium_fuel_rod', 2, 80),
        new ItemOfBag('modern_industrialization:uranium_fuel_rod_double', 1, 80),

        new ItemOfBag('modern_industrialization:turbo_machine_hull', 2, 35),
        new ItemOfBag('modern_industrialization:highly_advanced_machine_hull', 2, 35),
        new ItemOfBag('modern_industrialization:solid_titanium_machine_casing', 2, 35),
        new ItemOfBag('modern_industrialization:titanium_machine_casing_pipe',1,20),
        new ItemOfBag('modern_industrialization:space_casing', 2, 35),

        new ItemOfBag('neepmeat:advanced_motor',1,15),
        new ItemOfBag('neepmeat:control_unit',4,15),
        new ItemOfBag('neepmeat:integrator_egg',1,20),
        new ItemOfBag('neepmeat:enlightened_brain',6,20),
        new ItemOfBag('neepmeat:internal_components',8,20),

        new ItemOfBag('modern_industrialization:industrial_apiary',1,60),
        new ItemOfBag('modern_industrialization:electric_greenhouse',1,40),
        new ItemOfBag('modern_industrialization:void_pump',1,40),
        new ItemOfBag('modern_industrialization:photolithographer',1,15),
        new ItemOfBag('modern_industrialization:blast_alloy_smelter',1,25),
        new ItemOfBag('modern_industrialization:pressurizer',1,20),
        new ItemOfBag('modern_industrialization:implosion_compressor',1,20),
        new ItemOfBag('modern_industrialization:void_distillation_machine',1,10),
        
        new ItemOfBag('modern_industrialization:advanced_upgrade', 4, 20),
        new ItemOfBag('modern_industrialization:turbo_upgrade', 4, 20),

        new ItemOfBag('modern_industrialization:titanium_barrel', 1, 30),
        new ItemOfBag('modern_industrialization:titanium_tank', 1, 30),
        new ItemOfBag('modern_industrialization:titanium_drill', 8, 15),

        new ItemOfBag('modern_industrialization:annealed_copper_cable',16,40),
        new ItemOfBag('modern_industrialization:hv_steam_turbine', 2, 35),
        new ItemOfBag('modern_industrialization:large_steam_turbine',1,15),
    ]),
    epic: new Bag([
        new ItemOfBag('modern_industrialization:large_advanced_pump', 6, 30),
        new ItemOfBag('modern_industrialization:large_advanced_motor', 4, 30),
        new ItemOfBag('modern_industrialization:photonic_circuit_board', 2, 25),
        new ItemOfBag('modern_industrialization:processing_unit', 2, 25),
        new ItemOfBag('modern_industrialization:random_access_memory',4,40),
        new ItemOfBag('modern_industrialization:memory_management_unit',4,40),
        new ItemOfBag('modern_industrialization:arithmetic_logic_unit',4,40),
        new ItemOfBag('modern_industrialization:heat_exchanger',1,40),
        new ItemOfBag('modern_industrialization:highly_advanced_machine_hull',1,20),

        new ItemOfBag('modern_industrialization:titanium_ingot', 16, 80),
        new ItemOfBag('modern_industrialization:indium_phosphide_plate', 16, 80),
        new ItemOfBag('modern_industrialization:uranium_fuel_rod', 2, 80),
        new ItemOfBag('modern_industrialization:uranium_fuel_rod_double', 2, 40),
        new ItemOfBag('modern_industrialization:uranium_fuel_rod_quad', 2, 20),

        new ItemOfBag('modern_industrialization:turbo_machine_hull', 2, 35),
        new ItemOfBag('modern_industrialization:highly_advanced_machine_hull', 2, 35),
        new ItemOfBag('modern_industrialization:solid_titanium_machine_casing', 2, 35),
        new ItemOfBag('modern_industrialization:titanium_machine_casing_pipe',1,20),
        new ItemOfBag('modern_industrialization:space_casing', 2, 35),
        new ItemOfBag('modern_industrialization:space_miner', 1, 50),

        new ItemOfBag('neepmeat:enlightened_brain',4,40),
        new ItemOfBag('neepmeat:plc',1,15),
        new ItemOfBag('neepmeat:robotic_arm',2,15),
        new ItemOfBag('neepmeat:advanced_motor',1,25),
        new ItemOfBag('neepmeat:control_unit',4,25),
        new ItemOfBag('neepmeat:integrator_egg',1,40),
        new ItemOfBag('neepmeat:meat_steel_machine_block',8,70),
        new ItemOfBag('neepmeat:enlightened_brain',6,40),
        new ItemOfBag('neepmeat:internal_components',8,40),

        new ItemOfBag('modern_industrialization:industrial_apiary',1,60),
        new ItemOfBag('modern_industrialization:electric_greenhouse',1,40),
        new ItemOfBag('modern_industrialization:void_pump',1,40),
        new ItemOfBag('modern_industrialization:photolithographer',1,15),
        new ItemOfBag('modern_industrialization:blast_alloy_smelter',1,25),
        new ItemOfBag('modern_industrialization:pressurizer',1,40),
        new ItemOfBag('modern_industrialization:implosion_compressor',1,40),
        new ItemOfBag('modern_industrialization:void_distillation_machine',1,20),
        
        new ItemOfBag('modern_industrialization:advanced_upgrade', 4, 40),
        new ItemOfBag('modern_industrialization:turbo_upgrade', 4, 40),

        new ItemOfBag('modern_industrialization:titanium_barrel', 1, 60),
        new ItemOfBag('modern_industrialization:titanium_tank', 1, 60),
        new ItemOfBag('modern_industrialization:titanium_drill', 8, 30),

        new ItemOfBag('modern_industrialization:annealed_copper_cable',16,80),
        new ItemOfBag('modern_industrialization:hv_steam_turbine', 2, 70),
        new ItemOfBag('modern_industrialization:large_steam_turbine',1,30),
    ]),
};

let end = {
    uncommon: new Bag([
        new ItemOfBag('modern_industrialization:quantum_circuit_board',4,50),
        new ItemOfBag('neepmeat:skin_machine_block',16,50),
        new ItemOfBag('kubejs:photonic_circuit',8,50),           
        new ItemOfBag('modern_industrialization:gravichestplate',1,25),
        new ItemOfBag('modern_industrialization:space_miner',1,25), 
        new ItemOfBag('modern_industrialization:large_steam_turbine',1,25),
        new ItemOfBag('modern_industrialization:nuclear_reactor',1,15),
        new ItemOfBag('modern_industrialization:satellite',1,25),   
        new ItemOfBag('neepmeat:plc',1,100),
        new ItemOfBag('ad_astra:tier_4_rocket',1,20),
        new ItemOfBag('fluxnetworks:gargantuan_flux_storage',1,15), 
    ]),
    rare: new Bag([
        new ItemOfBag('kubejs:neutron_capturing_mesh',1,60),
        new ItemOfBag('ae2:spatial_pylon',16,50),
        new ItemOfBag('ae2:spatial_cell_component_2',25),
        new ItemOfBag('ae2:quantum_ring',2,15),
        new ItemOfBag('kubejs:photonic_circuit',16,50),
        new ItemOfBag('modern_industrialization:turbinium_steam_turbine',1,25),
        new ItemOfBag('modern_industrialization:containment_chamber',1,25),
        new ItemOfBag('modern_industrialization:molecular_deconstructor',1,25),
        new ItemOfBag('neepmeat:pylon',1,15),
        new ItemOfBag('modern_industrialization:quantum_circuit',1,5),
        new ItemOfBag('kubejs:nullodermal_affected_beehemoth',8,50),
        new ItemOfBag('kubejs:necrodermal_affected_beehemoth',8,50),
    ]),
    epic: new Bag([
        new ItemOfBag('modern_industrialization:fusion_construct',1,50),
        new ItemOfBag('modern_industrialization:fission_chamber',1,50),
        new ItemOfBag('modern_industrialization:fusion_reactor',1,50),
        new ItemOfBag('modern_industrialization:plasma_turbine',1,50),
        new ItemOfBag('modern_industrialization:drone_station',1,50),
        new ItemOfBag('neepmeat:charnel_pump',1,50),
        new ItemOfBag('modern_industrialization:quantum_upgrade',1,50),
        new ItemOfBag('modern_industrialization:naquadah_fuel_rod_quad',1,50),
        new ItemOfBag('modern_industrialization:particle_manipulator',1,50),
        new ItemOfBag('kubejs:mining_drone',4,25),
        new ItemOfBag('kubejs:neutronium_ingot',1,15),
        new ItemOfBag('kubejs:neutronium_augmented_aluminum_drill',1,5),
        new ItemOfBag('kubejs:neutronium_augmented_bronze_drill',1,5),
        new ItemOfBag('kubejs:neutronium_augmented_titanium_drill',1,5),
        new ItemOfBag('kubejs:neutronium_augmented_steel_drill',1,5),
        new ItemOfBag('kubejs:neutronium_augmented_stainless_steel_drill',1,5),
        new ItemOfBag('kubejs:neutronium_augmented_ostrum_drill',1,5),
        new ItemOfBag('kubejs:neutronium_augmented_gold_drill',1,5),
        new ItemOfBag('kubejs:neutronium_augmented_desh_drill',1,5),
        new ItemOfBag('kubejs:neutronium_augmented_copper_drill',1,5),
        new ItemOfBag('kubejs:neutronium_augmented_calorite_drill',1,5),
    ]),
};

function addBags(event, lootbagType, object) {
    for (let rarity of global.lootbagRarity) {
        event
            .addLootTableModifier(`lootbag:${lootbagType}/${rarity}`)
            .addWeightedLoot(
                object[rarity].itemQuantity,
                object[rarity].lootPool,
            )
    }
};

LootJS.modifiers((event) => {
    addBags(event, 'food', food)
    addBags(event, 'mob', mob)
    addBags(event, 'magic', magic)
    addBags(event, 'early', early)
    addBags(event, 'mid', mid)
    addBags(event, 'late', late)
    addBags(event, 'end', end)
});
