ServerEvents.recipes(event => {
    event.remove({id: 'buildinggadgets:template_manager'})
    event.remove({id: 'buildinggadgets:template'})
    event.remove({id: 'buildinggadgets:gadget_copy_paste'})
    event.remove({id: 'buildinggadgets:gadget_building'})
    event.remove({id: 'buildinggadgets:gadget_exchanging'})
    event.remove({id: 'buildinggadgets:gadget_destruction'})


    event.recipes.modern_industrialization.assembler(8, 400)
        .itemIn('modern_industrialization:analog_circuit')
        .itemIn('12x modern_industrialization:steel_plate')
        .itemIn('24x modern_industrialization:copper_wire')
        .itemIn('modern_industrialization:redstone_battery')
        .itemIn('kubejs:building_card')
        .fluidIn('modern_industrialization:soldering_alloy', 500)
        .itemOut('buildinggadgets:gadget_building')

    event.recipes.modern_industrialization.assembler(32, 1600)
        .itemIn('modern_industrialization:digital_circuit')
        .itemIn('12x modern_industrialization:stainless_steel_plate')
        .itemIn('kubejs:destruction_card')
        .itemIn('2x modern_industrialization:compactium_large_plate')
        .itemIn('24x modern_industrialization:platinum_fine_wire')
        .itemIn('modern_industrialization:compactium_battery')
        .fluidIn('modern_industrialization:soldering_alloy', 500)
        .itemOut('buildinggadgets:gadget_destruction')

    event.recipes.modern_industrialization.assembler(8, 400)
        .itemIn('modern_industrialization:analog_circuit')
        .itemIn('12x modern_industrialization:steel_plate')
        .itemIn('24x modern_industrialization:copper_wire')
        .itemIn('modern_industrialization:redstone_battery')
        .itemIn('kubejs:exchanging_card')
        .fluidIn('modern_industrialization:soldering_alloy', 500)
        .itemOut('buildinggadgets:gadget_exchanging')

    event.shapeless('kubejs:building_card', ['minecraft:grass_block', 'modern_industrialization:analog_circuit'])
    event.shapeless('kubejs:exchanging_card', ['mythicmetals:celestium_ingot', 'modern_industrialization:analog_circuit'])
    event.shapeless('kubejs:destruction_card', ['modern_industrialization:trash_can', 'modern_industrialization:analog_circuit'])

})
