ServerEvents.recipes(event => {
    event.remove({id: 'buildinggadgets:template_manager'})
    event.remove({id: 'buildinggadgets:template'})
    event.remove({id: 'buildinggadgets:gadget_copy_paste'})
    event.remove({id: 'buildinggadgets:gadget_building'})
    event.remove({id: 'buildinggadgets:gadget_exchanging'})
    event.remove({id: 'buildinggadgets:gadget_destruction'})


    event.recipes.modern_industrialization.assembler(4, 8000)
        .itemIn('modern_industrialization:digital_circuit')
        .itemIn('12x modern_industrialization:stainless_steel_plate')
        .itemIn('kubejs:building_card')
        .itemIn('2x modern_industrialization:compactium_large_plate')
        .itemIn('24x modern_industrialization:platinum_fine_wire')
        .itemIn('modern_industrialization:compactium_battery')
        .fluidIn('modern_industrialization:soldering_alloy', 500)
        .itemOut('buildinggadgets:gadget_building')

    event.recipes.modern_industrialization.assembler(4, 8000)
        .itemIn('modern_industrialization:digital_circuit')
        .itemIn('12x modern_industrialization:stainless_steel_plate')
        .itemIn('kubejs:desctruction_card')
        .itemIn('2x modern_industrialization:compactium_large_plate')
        .itemIn('24x modern_industrialization:platinum_fine_wire')
        .itemIn('modern_industrialization:compactium_battery')
        .fluidIn('modern_industrialization:soldering_alloy', 500)
        .itemOut('buildinggadgets:gadget_destruction')

    event.recipes.modern_industrialization.assembler(4, 8000)
        .itemIn('modern_industrialization:digital_circuit')
        .itemIn('12x modern_industrialization:stainless_steel_plate')
        .itemIn('kubejs:exchanging_card')
        .itemIn('2x modern_industrialization:compactium_large_plate')
        .itemIn('24x modern_industrialization:platinum_fine_wire')
        .itemIn('modern_industrialization:compactium_battery')
        .fluidIn('modern_industrialization:soldering_alloy', 500)
        .itemOut('buildinggadgets:gadget_exchanging')

    event.shapeless('kubejs:building_card', ['minecraft:grass_block', 'ae2:advanced_card'])
    event.shapeless('kubejs:exchanging_card', ['ae2:formation_core', 'ae2:advanced_card'])
    event.shapeless('kubejs:desctruction_card', ['modern_industrialization:trash_can', 'ae2:advanced_card'])

})