//priority: 0

ServerEvents.recipes(event => {
    //Compressor
    event.remove({ output: 'computercraft:pocket_computer_normal' })
    event.recipes.modern_industrialization.compressor(32, 1200)
        .itemIn('computercraft:computer_normal')
        .itemOut('computercraft:pocket_computer_normal')

    event.remove({ output: 'computercraft:pocket_computer_advanced' })
    event.recipes.modern_industrialization.compressor(32, 2400)
        .itemIn('computercraft:computer_advanced')
        .itemOut('computercraft:pocket_computer_advanced')

    //Assembler
    event.remove({ output: 'computercraft:computer_advanced' })
    event.recipes.modern_industrialization.assembler(8, 200)
        .itemIn('computercraft:computer_normal')
        .itemIn('modern_industrialization:highly_advanced_upgrade')
        .itemOut('computercraft:computer_advanced')

    event.remove({ output: 'computercraft:monitor_advanced' })
    event.recipes.modern_industrialization.assembler(8, 200)
        .itemIn('computercraft:monitor_normal')
        .itemIn('modern_industrialization:highly_advanced_upgrade')
        .itemOut('computercraft:monitor_advanced')

    event.remove({ output: 'computercraft:turtle_advanced' })
    event.recipes.modern_industrialization.assembler(8, 200)
        .itemIn('computercraft:turtle_normal')
        .itemIn('modern_industrialization:highly_advanced_upgrade')
        .itemOut('computercraft:turtle_advanced')

    event.remove({ output: 'computercraft:computer_normal' })
    event.recipes.modern_industrialization.assembler(8, 200)
        .itemIn('modern_industrialization:turbo_machine_hull')
        .itemIn('modern_industrialization:processing_unit')
        .itemIn('ae2:semi_dark_monitor')
        .itemIn('ae2:wireless_receiver')
        .itemIn('2x modern_industrialization:platinum_wire')
        .itemIn('ae2:calculation_processor')
        .itemIn('ae2:logic_processor')
        .itemIn('ae2:engineering_processor')
        .itemOut('computercraft:computer_normal')

    event.remove({ output: 'computercraft:disk_drive' })
    event.recipes.modern_industrialization.assembler(8, 200)
        .itemIn('modern_industrialization:basic_machine_hull')
        .itemIn('ae2:item_cell_housing')
        .itemIn('2x modern_industrialization:silver_wire')
        .itemIn('8x modern_industrialization:aluminum_bolt')
        .itemIn('modern_industrialization:piston')
        .itemOut('computercraft:disk_drive')

    event.remove({ output: 'computercraft:wireless_modem_advanced' })
    event.recipes.modern_industrialization.assembler(8, 200)
        .itemIn('computercraft:wireless_modem_normal')
        .itemIn('architects_palette:ender_pearl_block')
        .itemIn('minecraft:sculk_sensor')
        .itemOut('computercraft:wireless_modem_advanced')

    event.remove({ output: 'computercraft:monitor_normal' })
    event.recipes.modern_industrialization.assembler(8, 200)
        .itemIn('modern_industrialization:basic_machine_hull')
        .itemIn('ae2:semi_dark_monitor')
        .itemIn('modern_industrialization:silver_wire')
        .itemIn('4x modern_industrialization:diode')
        .itemIn('modern_industrialization:silicon_battery')
        .itemOut('computercraft:monitor_normal')

    event.remove({ output: 'computercraft:cable' })
    event.recipes.modern_industrialization.assembler(8, 200)
        .itemIn('3x ae2:quartz_fiber')
        .itemIn('modern_industrialization:silicon_plate')
        .itemOut('16x computercraft:cable')

    event.remove({ output: 'computercraft:printer' })
    event.recipes.modern_industrialization.assembler(8, 200)
        .itemIn('modern_industrialization:basic_machine_hull')
        .itemIn('ae2:equal_distribution_card')
        .itemIn('minecraft:black_dye')
        .itemIn('3x modern_industrialization:silver_wire')
        .itemOut('computercraft:printer')

    event.remove({ output: 'computercraft:speaker' })
    event.recipes.modern_industrialization.assembler(8, 200)
        .itemIn('modern_industrialization:basic_machine_hull')
        .itemIn('minecraft:note_block')
        .itemIn('modern_industrialization:silver_wire')
        .itemIn('2x modern_industrialization:redstone_battery')
        .itemIn('minecraft:black_wool')
        .itemOut('computercraft:speaker')

    event.remove({ output: 'computercraft:turtle_normal' })
    event.recipes.modern_industrialization.assembler(8, 200)
        .itemIn('computercraft:computer_normal')
        .itemIn('modern_industrialization:advanced_pump')
        .itemIn('2x modern_industrialization:robot_arm')
        .itemIn('modern_industrialization:large_motor')
        .itemIn('ae2:portable_item_cell_16k')
        .itemIn('ae2:energy_card')
        .itemOut('computercraft:turtle_normal')

    event.remove({ output: 'computercraft:wired_modem' })
    event.recipes.modern_industrialization.assembler(8, 200)
        .itemIn('8x computercraft:cable')
        .itemIn('ae2:me_p2p_tunnel')
        .itemIn('minecraft:redstone')
        .itemOut('computercraft:wired_modem')

    event.remove({ output: 'computercraft:wireless_modem_normal' })
    event.recipes.modern_industrialization.assembler(8, 200)
        .itemIn('computercraft:wired_modem')
        .itemIn('ae2:wireless_receiver')
        .itemIn('ae2:wireless_booster')
        .itemOut('computercraft:wireless_modem_normal')
})
