
ServerEvents.recipes(event => {
    // Advanced Ejector
    event.remove({id: 'neepmeat:item_transfer/advanced_ejector'})
    event.recipes.modern_industrialization.assembler(16, 200)
        .itemIn('neepmeat:enlightened_brain')
        .itemIn('neepmeat:filtered_ejector')
        .itemIn('2x modern_industrialization:stainless_steel_curved_plate')
        .itemIn('4x modern_industrialization:meat_steel_ring')
        .fluidIn('neepmeat:work_fluid', 100)
        .fluidIn('modern_industrialization:soldering_alloy', 50)
        .itemOut('neepmeat:advanced_ejector')
        .biome('ad_astra:orbit')
    // PID Controller
    event.remove({id: 'neepbus:pid_controller'})
    event.recipes.modern_industrialization.assembler(16, 300)
        .itemIn('4x modern_industrialization:meat_steel_plate')
        .itemIn('neepmeat:control_unit')
        .itemIn('4x neepmeat:data_cable')
        .itemIn('4x minecraft:glass_pane')
        .itemIn('2x ae2:logic_processor')
        .itemIn('2x ae2:calculation_processor')
        .fluidIn('neepmeat:work_fluid', 50)
        .fluidIn('modern_industrialization:molten_redstone', 150)
        .itemOut('neepmeat:pid_controller')
        .biome('ad_astra:orbit')
    // Bottler
    event.remove({id: 'neepmeat:fluid_transfer/bottler'})
    event.recipes.modern_industrialization.assembler(16, 300)
        .itemIn('4x modern_industrialization:stainless_steel_large_plate')
        .itemIn('modern_industrialization:pump')
        .itemIn('neepmeat:enlightened_brain')
        .itemIn('4x minecraft:glass_pane')
        .fluidIn('neepmeat:work_fluid', 50)
        .itemOut('neepmeat:bottler')
        .biome('ad_astra:orbit')
    // Stomach
    event.remove({id: 'neepmeat:machines/living_machine/stomach'})
    event.recipes.modern_industrialization.assembler(32, 400)
        .itemIn('8x neepmeat:skin_machine_block')
        .itemIn('4x neepmeat:meat_steel_component')
        .itemIn('4x modern_industrialization:large_advanced_pump')
        .itemIn('modern_industrialization:large_heat_exchanger')
        .itemIn('16x modern_industrialization:meat_steel_large_plate')
        .itemIn('4x modern_industrialization:steel_rod')
        .fluidIn('neepmeat:work_fluid',350)
        .itemOut('neepmeat:stomach')
        .biome('ad_astra:orbit')
    // Farming Scutter
    event.remove({id: 'neepmeat:machines/farming_scutter'})
    event.recipes.modern_industrialization.assembler(8, 200)
        .itemIn('neepmeat:enlightened_brain')
        .itemIn('2x neepmeat:internal_components')
        .itemIn('neepmeat:integration_charge_crude')
        .itemIn('ae2:calculation_processor')
        .itemIn('ae2:engineering_processor')
        .fluidIn('neepmeat:work_fluid',100)
        .itemOut('neepmeat:farming_scutter')
        .biome('ad_astra:orbit')

    // Redstone Transducer
    event.remove({id: 'neepbus:redstone_transducer'})
    event.recipes.modern_industrialization.assembler(8, 200)
        .itemIn('neepmeat:data_cable')
        .itemIn('ae2:redstone_card')
        .itemIn('ae2:semi_dark_monitor')
        .fluidIn('neepmeat:work_fluid',150)
        .itemOut('neepmeat:redstone_transducer')
        .biome('ad_astra:orbit')

    // Vertical Gauge
    event.remove({id: 'neepbus:vertical_gauge'})
    event.recipes.modern_industrialization.assembler(8, 200)
        .itemIn('neepmeat:data_cable')
        .itemIn('ae2:capacity_card')
        .itemIn('ae2:semi_dark_monitor')
        .fluidIn('neepmeat:work_fluid',150)
        .itemOut('neepmeat:vertical_gauge')
        .biome('ad_astra:orbit')

    // Slider
    event.remove({id: 'neepbus:slider'})
    event.recipes.modern_industrialization.assembler(8, 200)
        .itemIn('neepmeat:data_cable')
        .itemIn('ae2:fuzzy_card')
        .itemIn('ae2:semi_dark_monitor')
        .fluidIn('neepmeat:work_fluid',150)
        .itemOut('neepmeat:slider')
        .biome('ad_astra:orbit')

    // Large Trommel
    event.remove({id: 'neepmeat:manufacture/charnel_pump'})
    event.recipes.modern_industrialization.assembler(64, 2400)
        .itemIn("2x kubejs:photonic_circuit")
        .itemIn("16x ae2:quartz_vibrant_glass")
        .itemIn("32x modern_industrialization:meat_steel_large_plate")
        .itemIn("32x modern_industrialization:blastproof_alloy_large_plate")
        .itemIn("9x neepmeat:meat_steel_machine_block")
        .itemIn("16x modern_industrialization:indium_phosphide_large_plate")
        .itemIn("64x modern_industrialization:cupronickel_wire_magnetic")
        .itemIn("64x modern_industrialization:stainless_steel_rod_magnetic")
        .itemIn("16x modern_industrialization:large_advanced_pump")
        .fluidIn('neepmeat:charged_work_fluid',4000)
        .fluidIn('modern_industrialization:argon',1000)
        .itemOut('neepmeat:charnel_pump')
        .biome('ad_astra:orbit')
    // Hydraulic Press
    event.remove({id: 'neepmeat:machines/hydraulic_press'})
    event.recipes.modern_industrialization.assembler(8, 200)
        .itemIn("8x modern_industrialization:iron_large_plate")
        .itemIn("4x modern_industrialization:bronze_plate")
        .itemIn("4x modern_industrialization:piston")
        .itemIn("16x modern_industrialization:fluid_pipe")
        .itemIn("modern_industrialization:large_pump")
        .fluidIn('modern_industrialization:soldering_alloy',150)
        .itemOut('neepmeat:hydraulic_press')
    // Large Trommel
    event.remove({id: 'neepmeat:machines/living_machine/large_trommel'})
    event.recipes.modern_industrialization.assembler(16, 400)
        .itemIn('4x neepmeat:meat_steel_component')
        .itemIn('4x modern_industrialization:large_advanced_motor')
        .itemIn('2x modern_industrialization:large_advanced_pump')
        .itemIn('3x ae2:engineering_processor')
        .itemIn('8x modern_industrialization:steel_large_plate')
        .itemIn('16x modern_industrialization:bronze_large_plate')
        .itemIn('64x minecraft:iron_bars')
        .itemIn('modern_industrialization:large_heat_exchanger')
        .fluidIn('neepmeat:work_fluid',350)
        .itemOut('neepmeat:large_trommel')
        .biome('ad_astra:orbit')
    // Crusher Segment
    event.remove({id: 'neepmeat:machines/living_machine/crushing_segment'})
    event.recipes.modern_industrialization.assembler(16, 400)
        .itemIn('4x neepmeat:meat_steel_component')
        .itemIn('12x modern_industrialization:invar_rotary_blade')
        .itemIn('8x modern_industrialization:large_motor')
        .itemIn('3x ae2:engineering_processor')
        .itemIn('16x modern_industrialization:steel_large_plate')
        .itemIn('modern_industrialization:large_heat_exchanger')
        .fluidIn('neepmeat:work_fluid',350)
        .itemOut('neepmeat:crusher_segment')
        .biome('ad_astra:orbit')
    // Integration Port
    event.remove({id: 'neepmeat:machines/living_machine/integration_port'})
    event.recipes.modern_industrialization.assembler(16, 400)
        .itemIn('neepmeat:machine_block')
        .itemIn('2x modern_industrialization:advanced_pump')
        .itemIn('neepmeat:fluid_rationer')
        .itemIn('2x neepmeat:meat_steel_component')
        .itemIn('ae2:engineering_processor')
        .fluidIn('neepmeat:work_fluid',150)
        .itemOut('neepmeat:integration_port')
        .biome('ad_astra:orbit')

    // Largest Hopper
    event.recipes.modern_industrialization.assembler(16, 400)
        .itemIn('4x minecraft:hopper')
        .itemIn('32x modern_industrialization:bronze_large_plate')
        .itemIn('16x modern_industrialization:meat_steel_curved_plate')
        .itemIn('4x modern_industrialization:piston')
        .itemOut('neepmeat:largest_hopper')
        .fluidIn('neepmeat:work_fluid',150)
        .biome('ad_astra:orbit')

    // Meat Steel Machine Block
    event.recipes.modern_industrialization.assembler(16, 400)
        .itemIn('neepmeat:meat_steel_component')
        .itemIn('4x modern_industrialization:meat_steel_large_plate')
        .itemIn('2x neepmeat:internal_components')
        .itemIn('neepmeat:control_unit')
        .itemIn('3x ae2:engineering_processor')
        .itemOut('neepmeat:meat_steel_machine_block')
        .fluidIn('neepmeat:work_fluid',150)
        .biome('ad_astra:orbit')

    // Blood Bubble Machine Block
    event.recipes.modern_industrialization.assembler(16, 400)
        .itemIn('neepmeat:blood_bubble_log')
        .itemIn('4x modern_industrialization:steel_ring')
        .itemIn('neepmeat:internal_components')
        .fluidIn('neepmeat:work_fluid',150)
        .itemOut('neepmeat:blood_bubble_machine_block')
        .biome('ad_astra:orbit')

    // Machine Controller
    event.recipes.modern_industrialization.assembler(16, 400)
        .itemIn('neepmeat:machine_block')
        .itemIn('2x neepmeat:control_unit')
        .itemIn('neepmeat:enlightened_brain')
        .itemIn('4x ae2:engineering_processor')
        .itemIn('6x ae2:logic_processor')
        .fluidIn('neepmeat:work_fluid',400)
        .itemOut('neepmeat:living_machine_controller')
        .biome('ad_astra:orbit')

    // Motor Port
    event.recipes.modern_industrialization.assembler(16, 400)
        .itemIn('neepmeat:machine_block')
        .itemIn('neepmeat:internal_components')
        .itemIn('modern_industrialization:large_motor')
        .itemIn('6x modern_industrialization:cupronickel_wire_magnetic')
        .itemOut('neepmeat:motor_port')
        .biome('ad_astra:orbit')

    // Machine Block
    event.recipes.modern_industrialization.assembler(16, 400)
        .itemIn('4x modern_industrialization:bronze_large_plate')
        .itemIn('neepmeat:internal_components')
        .itemIn('2x modern_industrialization:electronic_circuit')
        .itemIn('6x modern_industrialization:cupronickel_wire_magnetic')
        .itemOut('neepmeat:machine_block')
        .fluidIn('neepmeat:work_fluid',200)
        .biome('ad_astra:orbit')

    // Pipe Driver
    event.recipes.modern_industrialization.assembler(16, 400)
        .itemIn('4x modern_industrialization:netherite_plate')
        .itemIn('8x minecraft:rotten_flesh')
        .itemIn('neepmeat:router')
        .itemIn('2x modern_industrialization:electronic_circuit')
        .itemIn('8x modern_industrialization:redstone_alloy_plate')
        .itemOut('neepmeat:pipe_driver')

    event.remove({ id: 'neepmeat:ingredients/control_unit' })
    event.recipes.modern_industrialization.assembler(32, 200)
        .itemIn('neepmeat:internal_components')
        .itemIn('neepmeat:enlightened_brain')
        .itemIn('2x modern_industrialization:arithmetic_logic_unit')
        .itemIn('4x ae2:sky_dust')
        .fluidIn('neepmeat:work_fluid', 200)
        .itemOut('neepmeat:control_unit')
        .biome('ad_astra:orbit')

    event.remove({ id: 'neepmeat:ingredients/internal_components' })
    event.recipes.modern_industrialization.assembler(32, 200)
        .itemIn('neepmeat:integration_charge_crude')
        .itemIn('modern_industrialization:piston')
        .itemIn('modern_industrialization:pump')
        .itemIn('2x modern_industrialization:motor')
        .itemIn('4x minecraft:rotten_flesh')
        .fluidIn('neepmeat:work_fluid', 200)
        .itemOut('neepmeat:internal_components')
        .biome('ad_astra:orbit')

    event.remove({ id: 'neepmeat:cable/vascular_conduit' })
    event.recipes.modern_industrialization.assembler(32, 200)
        .itemIn('4x modern_industrialization:meat_steel_curved_plate')
        .itemIn('2x modern_industrialization:yttrium_plate')
        .itemIn('2x neepmeat:internal_components')
        .itemIn('neepmeat:flesh_potato')
        .fluidIn('neepmeat:work_fluid', 200)
        .itemOut('8x neepmeat:vascular_conduit')
        .biome('ad_astra:orbit')

    event.remove({ id: 'neepmeat:cable/data_cable' })
    event.recipes.modern_industrialization.assembler(16, 200)
        .itemIn('4x modern_industrialization:platinum_fine_wire')
        .itemIn('2x computercraft:cable')
        .itemIn('2x modern_industrialization:meat_steel_curved_plate')
        .itemIn('8x modern_industrialization:redstone_alloy_nugget')
        .fluidIn('modern_industrialization:styrene_butadiene_rubber', 20)
        .itemOut('4x neepmeat:data_cable')
        .biome('ad_astra:orbit')

    event.recipes.modern_industrialization.assembler(16, 200)
        .itemIn('2x modern_industrialization:meat_steel_rod')
        .itemIn('modern_industrialization:meat_steel_curved_plate')
        .itemIn('2x modern_industrialization:meat_steel_ring')
        .fluidIn('modern_industrialization:soldering_alloy', 200)
        .itemOut('neepmeat:meat_steel_component')
        .biome('ad_astra:orbit')


    event.recipes.modern_industrialization.assembler(64, 600)
        .itemIn('computercraft:turtle_normal')
        .itemIn('2x neepmeat:internal_components')
        .itemIn('6x neepmeat:control_unit')
        .itemIn('4x neepmeat:meat_steel_component')
        .itemIn('2x neepmeat:enlightened_brain')
        .itemIn('8x ae2:logic_processor')
        .itemIn('8x ae2:calculation_processor')
        .itemIn('8x ae2:engineering_processor')
        .fluidIn('neepmeat:charged_work_fluid', 300)
        .itemOut('neepmeat:plc')
        .biome('ad_astra:orbit')

    event.recipes.modern_industrialization.assembler(16, 300)
        .itemIn('modern_industrialization:large_motor')
        .itemIn('2x neepmeat:bioelectric_organ')
        .itemIn('neepmeat:integration_charge_crude')
        .itemIn('4x modern_industrialization:bronze_large_plate')
        .fluidIn('neepmeat:work_fluid', 200)
        .itemOut('neepmeat:motor_unit')
        .biome('ad_astra:orbit')

    event.recipes.modern_industrialization.assembler(32, 300)
        .itemIn('modern_industrialization:large_advanced_motor')
        .itemIn('4x neepmeat:bioelectric_organ')
        .itemIn('neepmeat:integration_charge_crude')
        .itemIn('4x modern_industrialization:meat_steel_large_plate')
        .fluidIn('neepmeat:work_fluid', 200)
        .itemOut('neepmeat:advanced_motor')
        .biome('ad_astra:orbit')

    event.recipes.modern_industrialization.assembler(32, 300)
        .itemIn('4x modern_industrialization:bronze_large_plate')
        .itemIn('modern_industrialization:large_motor')
        .itemIn('neepmeat:enlightened_brain')
        .itemIn('2x modern_industrialization:meat_steel_curved_plate')
        .itemIn('modern_industrialization:stainless_steel_drill')
        .fluidIn('neepmeat:work_fluid', 100)
        .itemOut('neepmeat:breaker')
        .biome('ad_astra:orbit')

    event.recipes.modern_industrialization.assembler(32, 300)
        .itemIn('4x modern_industrialization:bronze_large_plate')
        .itemIn('2x modern_industrialization:piston')
        .itemIn('neepmeat:enlightened_brain')
        .itemIn('2x modern_industrialization:meat_steel_curved_plate')
        .itemIn('4x minecraft:glass_pane')
        .fluidIn('neepmeat:work_fluid', 100)
        .itemOut('neepmeat:deployer')
        .biome('ad_astra:orbit')

    event.recipes.modern_industrialization.assembler(32, 300)
        .itemIn('ae2:redstone_card')
        .itemIn('3x modern_industrialization:meat_steel_large_plate')
        .itemIn('modern_industrialization:redstone_control_module')
        .itemIn('4x modern_industrialization:redstone_alloy_plate')
        .itemIn('2x neepmeat:control_unit')
        .fluidIn('neepmeat:work_fluid', 100)
        .itemOut('neepmeat:redstone_interface')
        .biome('ad_astra:orbit')

    event.recipes.modern_industrialization.assembler(16, 200)
        .itemIn('neepmeat:internal_components')
        .itemIn('2x modern_industrialization:analog_circuit')
        .itemIn('4x modern_industrialization:annealed_copper_wire')
        .itemIn('2x modern_industrialization:cupronickel_wire_magnetic')
        .fluidIn('neepmeat:work_fluid', 100)
        .itemOut('neepmeat:bioelectric_organ')
        .biome('ad_astra:orbit')

    event.recipes.modern_industrialization.assembler(32, 400)
        .itemIn('modern_industrialization:stainless_steel_ring')
        .itemIn('neepmeat:control_unit')
        .itemIn('neepmeat:open_eye')
        .itemIn('2x ae2:quartz_vibrant_glass')
        .itemIn('4x modern_industrialization:platinum_fine_wire')
        .fluidIn('neepmeat:work_fluid', 100)
        .itemOut('neepmeat:goggles')
        .biome('ad_astra:orbit')

    event.recipes.modern_industrialization.assembler(32, 400)
        .itemIn('8x modern_industrialization:annealed_copper_wire')
        .itemIn('3x neepmeat:bioelectric_organ')
        .itemIn('neepmeat:fluid_buffer')
        .itemIn('2x neepmeat:meat_steel_component')
        .itemIn('modern_industrialization:advanced_pump')
        .itemIn('4x modern_industrialization:meat_steel_large_plate')
        .fluidIn('neepmeat:charged_work_fluid', 200)
        .itemOut('neepmeat:fluid_exciter')
        .biome('ad_astra:orbit')

    event.recipes.modern_industrialization.assembler(16, 200)
        .itemIn('4x modern_industrialization:invar_plate')
        .itemIn('2x neepmeat:bioelectric_organ')
        .itemIn('neepmeat:internal_components')
        .itemIn('4x modern_industrialization:kanthal_wire')
        .itemIn('modern_industrialization:small_heat_exchanger')
        .itemIn('2x neepmeat:meat_steel_component')
        .fluidIn('neepmeat:work_fluid', 200)
        .itemOut('neepmeat:heater')
        .biome('ad_astra:orbit')

    event.recipes.modern_industrialization.assembler(16, 200)
        .itemIn('3x modern_industrialization:meat_steel_plate')
        .itemIn('neepmeat:feeding_trough')
        .itemIn('modern_industrialization:invar_rotary_blade')
        .itemIn('2x neepmeat:fluid_pipe')
        .itemIn('2x modern_industrialization:steel_gear')
        .fluidIn('neepmeat:work_fluid', 200)
        .itemOut('neepmeat:item_mincer')
        .biome('ad_astra:orbit')

    event.recipes.modern_industrialization.assembler(32, 200)
        .itemIn('4x modern_industrialization:meat_steel_large_plate')
        .itemIn('neepmeat:control_unit')
        .itemIn('neepmeat:fluid_buffer')
        .itemIn('4x modern_industrialization:steel_gear')
        .itemIn('2x modern_industrialization:invar_rotary_blade')
        .fluidIn('neepmeat:work_fluid', 300)
        .itemOut('neepmeat:mincer')
        .biome('ad_astra:orbit')
    // Replace input
    event.replaceInput({id: 'ae2:decorative/quartz_fixture'}, 'minecraft:iron_ingot', 'modern_industrialization:iron_ring')
})
