
ServerEvents.recipes(event => {
    event.recipes.modern_industrialization.mixer(4, 100)
        .itemIn('#c:grains')
        .fluidIn('minecraft:water',250)
        .fluidIn('neepmeat:meat',50)
        .fluidOut('neepmeat:animal_feed',300)
    event.recipes.modern_industrialization.mixer(4, 100)
        .itemIn('neepmeat:flesh_potato')
        .fluidIn('minecraft:water',300)
        .fluidOut('neepmeat:eldritch_enzymes',300)
        .biome('ad_astra:orbit')
    event.recipes.modern_industrialization.mixer(16, 200)
        .itemIn('neepmeat:integration_charge_crude')
        .fluidIn('neepmeat:blood',120)
        .fluidIn('neepmeat:meat',120)
        .fluidOut('neepmeat:work_fluid',120)
        .biome('ad_astra:orbit')
    event.recipes.modern_industrialization.mixer(4, 200)
        .itemIn('minecraft:sugar')
        .fluidIn('neepmeat:pasteurised_milk',150)
        .fluidIn('neepmeat:meat',150)
        .fluidOut('neepmeat:pinkdrink',300)
    event.recipes.modern_industrialization.mixer(4, 200)
        .itemIn('minecraft:lapis_lazuli')
        .fluidIn('minecraft:water',100)
        .fluidOut('neepmeat:patina_treatment',120)
    event.remove({input: 'minecraft:redstone',output: 'wiredredstone:ender_redstone_mixture'});
    event.recipes.modern_industrialization.mixer(16, 200)
        .itemIn('4x modern_industrialization:beryllium_tiny_dust')
        .itemIn('4x minecraft:redstone')
        .itemIn('ae2:ender_dust')
        .itemOut('2x wiredredstone:ender_redstone_mixture')
})
