
ServerEvents.recipes(event => {
    event.recipes.modern_industrialization.mixer(4, 100)
        .itemIn('#c:grains')
        .fluidIn('minecraft:water',250)
        .fluidIn('neepmeat:meat',83)
        .fluidOut('neepmeat:animal_feed',333)
    event.recipes.modern_industrialization.mixer(4, 100)
        .itemIn('neepmeat:flesh_potato')
        .fluidIn('minecraft:water',333)
        .fluidOut('neepmeat:eldritch_enzymes',333)
        .biome('ad_astra:orbit')
    event.recipes.modern_industrialization.mixer(16, 200)
        .itemIn('neepmeat:integration_charge_crude')
        .fluidIn('neepmeat:blood',111)
        .fluidIn('neepmeat:meat',111)
        .fluidOut('neepmeat:work_fluid',111)
        .biome('ad_astra:orbit')
    event.recipes.modern_industrialization.mixer(4, 200)
        .itemIn('minecraft:sugar')
        .fluidIn('neepmeat:pasteurised_milk',166)
        .fluidIn('neepmeat:meat',166)
        .fluidOut('neepmeat:pinkdrink',333)
    event.recipes.modern_industrialization.mixer(4, 200)
        .itemIn('minecraft:lapis_lazuli')
        .fluidIn('minecraft:water',111)
        .fluidOut('neepmeat:patina_treatment',111)
    event.remove({input: 'minecraft:redstone',output: 'wiredredstone:ender_redstone_mixture'});
    event.recipes.modern_industrialization.mixer(16, 200)
        .itemIn('4x modern_industrialization:beryllium_tiny_dust')
        .itemIn('4x minecraft:redstone')
        .itemIn('ae2:ender_dust')
        .itemOut('2x wiredredstone:ender_redstone_mixture')
})
