
ServerEvents.recipes(event => {
    // Random Access Memory Caterium alternate
    event.recipes.modern_industrialization.chemical_reactor(12, 400)
        .itemIn('modern_industrialization:silicon_wafer')
        .itemIn('modern_industrialization:antimony_dust')
        .itemIn('modern_industrialization:caterium_dust')
        .fluidIn('modern_industrialization:argon',250)
        .fluidIn('modern_industrialization:styrene_butadiene_rubber',500)
        .itemOut('4x modern_industrialization:random_access_memory')
    // Naquadah Sulfuric Solution 
    event.recipes.modern_industrialization.chemical_reactor(12, 400)
        .itemIn('kubejs:raw_naquadah')
        .fluidIn('modern_industrialization:sulfuric_acid',9000)
        .fluidOut('modern_industrialization:naquadah_sulfuric_solution',9000)
    // Refined Caterium 
    event.recipes.modern_industrialization.chemical_reactor(12, 400)
        .itemIn('5x modern_industrialization:caterium_dust')
        .itemIn('2x modern_industrialization:calcium_metasilicate_dust')
        .itemIn('modern_industrialization:niobium_tiny_dust')
        .fluidIn('modern_industrialization:silicon_tetrafluoride_gas',1200)
        .fluidIn('modern_industrialization:hydrochloric_acid',600)
        .fluidIn('neepmeat:compressed_air',12000)
        .fluidOut('modern_industrialization:chlorine',500)
        .fluidOut('modern_industrialization:fluorine_gas',400)
        .itemOut('4x kubejs:refined_caterium')
        .itemOut('3x modern_industrialization:silicon_dust')

    event.recipes.modern_industrialization.chemical_reactor(10, 80)
        .itemIn('minecraft:ender_pearl')
        .fluidIn('modern_industrialization:ender_air', 2000)
        .fluidIn('modern_industrialization:void', 50)
        .fluidIn('neepmeat:compressed_air', 1000)
        .itemOut('2x minecraft:ender_pearl')
        .biome('ad_astra:orbit')
})
