ServerEvents.recipes(event => {
    // Algal Blend
    event.recipes.modern_industrialization.mixer(2, 100)
        .itemIn('2x minecraft:clay_ball')
        .itemIn('minecraft:kelp')
        .itemOut('4x architects_palette:algal_blend')
    // HSAL steel dsut
    event.recipes.modern_industrialization.mixer(2, 100)
        .itemIn('modern_industrialization:chromium_dust')
        .itemIn('6x modern_industrialization:iron_dust')
        .itemIn('modern_industrialization:molybdenum_dust')
        .itemIn('modern_industrialization:vanadium_dust')
        .itemOut('9x modern_industrialization:hsla_steel_dust')

    // Quartz blend dust
    event.recipes.modern_industrialization.mixer(6, 100)
        .itemIn('ad_astra:ice_shard')
        .itemIn('ae2:certus_quartz_dust')
        .itemIn('modern_industrialization:quartz_dust')
        .fluidIn('minecraft:water', 1000)
        .itemOut('2x modern_industrialization:quartz_blend_dust')

    // Cerebral plate
    event.recipes.modern_industrialization.mixer(2, 100)
        .itemIn('minecraft:tuff')
        .itemIn('modern_industrialization:salt_crushed_dust')
        .fluidIn('modern_industrialization:creosote', 500)
        .fluidIn('minecraft:water', 1000)
        .itemOut('16x architects_palette:cerebral_plate')

    //Fire clay dust
    event.remove({ id: 'modern_industrialization:materials/mixer/fire_clay_dust' })
    event.recipes.modern_industrialization.mixer(2, 100)
        .itemIn('2x architects_palette:algal_blend')
        .itemIn('2x modern_industrialization:brick_dust')
        .itemOut('4x modern_industrialization:fire_clay_dust')
    //lmao cheese
    event.recipes.modern_industrialization.mixer(2, 100)
        .itemIn('minecraft:apple')
        .itemIn('2x minecraft:glow_berries')
        .itemOut('expandeddelight:cheese_wheel')
        .fluidIn('milk:still_milk', 1000)


    event.recipes.modern_industrialization.mixer(2, 100)
        .itemIn('bewitchment:mandrake_root')
        .itemIn('kubejs:moth_wings')
        .itemIn('minecraft:feather')
        .itemIn('bewitchment:juniper_bark')
        .itemOut('bewitchment:heaven_extract')
        .fluidIn('minecraft:water', 250)
    event.recipes.modern_industrialization.mixer(2, 100)
        .itemIn('bewitchment:oak_bark')
        .itemIn('kubejs:moth_wings')
        .itemIn('minecraft:charcoal')
        .itemIn('minecraft:poppy')
        .itemOut('bewitchment:fiery_serum')
        .fluidIn('minecraft:water', 250)
    event.recipes.modern_industrialization.mixer(2, 100)
        .itemIn('bewitchment:belladonna')
        .itemIn('kubejs:moth_wings')
        .itemIn('bewitchment:cypress_bark')
        .itemIn('bewitchment:snake_tongue')
        .itemOut('bewitchment:grim_elixir')
        .fluidIn('minecraft:water', 250)
    event.recipes.modern_industrialization.mixer(2, 100)
        .itemIn('minecraft:kelp')
        .itemIn('kubejs:moth_wings')
        .itemIn('bewitchment:birch_bark')
        .itemIn('minecraft:cooked_cod')
        .itemOut('bewitchment:aqua_cerate')
        .fluidIn('minecraft:water', 250)
    event.recipes.modern_industrialization.mixer(2, 100)
        .itemIn('minecraft:stone')
        .itemIn('kubejs:moth_wings')
        .itemIn('bewitchment:spruce_bark')
        .itemIn('bewitchment:aconite')
        .itemOut('bewitchment:earth_ichor')
        .fluidIn('minecraft:water', 250)
    event.recipes.modern_industrialization.mixer(2, 100)
        .itemIn('modern_industrialization:salt_dust')
        .itemIn('kubejs:moth_wings')
        .itemIn('bewitchment:elder_bark')
        .itemIn('bewitchment:garlic')
        .itemOut('bewitchment:cleansing_balm')
        .fluidIn('minecraft:water', 250)
    event.recipes.modern_industrialization.mixer(2, 20)
        .itemIn('8x farmersdelight:rice')
        .fluidIn('minecraft:water', 500)
        .fluidOut('milk:still_milk', 500)
    
    event.recipes.modern_industrialization.mixer(2, 100)
        .itemIn('minecraft:clay')
        .itemIn('minecraft:dirt')
        .itemIn('spectrum:mermaids_gem')
        .fluidIn('minecraft:water', 1000)
        .fluidOut('spectrum:mud', 1000)

    event.recipes.modern_industrialization.mixer(8, 400)
        .itemIn('2x modern_industrialization:nickel_ingot')
        .itemIn('modern_industrialization:aluminum_ingot')
        .itemIn('minecraft:iron_ingot')
        .itemOut('kubejs:demagnetized_magnet_part')
})
