ServerEvents.recipes(event => {
    event.recipes.modern_industrialization.sifting_machine(4, 400)
        .itemIn('ad_astra:moon_sand')
        .itemOut('modern_industrialization:iron_tiny_dust', 0.01)
        .itemOut('modern_industrialization:desh_tiny_dust', 0.01)
        .itemOut('modern_industrialization:aluminum_tiny_dust', 0.01)
        .itemOut('modern_industrialization:titanium_tiny_dust', 0.01)
        .itemOut('modern_industrialization:chromium_tiny_dust', 0.01)

    event.recipes.modern_industrialization.sifting_machine(4, 400)
        .itemIn('ad_astra:mars_sand')
        .itemOut('modern_industrialization:iron_tiny_dust', 0.01)
        .itemOut('modern_industrialization:ostrum_tiny_dust', 0.01)
        .itemOut('modern_industrialization:aluminum_tiny_dust', 0.01)
        .itemOut('modern_industrialization:uranium_tiny_dust', 0.01)
        .itemOut('modern_industrialization:diamond_tiny_dust', 0.01)
        .itemOut('modern_industrialization:copper_tiny_dust', 0.01)
        .itemOut('modern_industrialization:platinum_tiny_dust', 0.01)
        .itemOut('modern_industrialization:gold_tiny_dust', 0.01)
        .itemOut('modern_industrialization:tungsten_tiny_dust', 0.01)

    event.recipes.modern_industrialization.sifting_machine(4, 400)
        .itemIn('ad_astra:venus_sand')
        .itemOut('modern_industrialization:gold_tiny_dust', 0.01)
        .itemOut('modern_industrialization:diamond_tiny_dust', 0.01)
        .itemOut('modern_industrialization:lead_tiny_dust', 0.01)
        .itemOut('modern_industrialization:coal_tiny_dust', 0.01)
        .itemOut('modern_industrialization:calorite_tiny_dust', 0.01)

    event.recipes.modern_industrialization.sifting_machine(4, 400)
        .itemIn('minecraft:sand')
        .itemOut('minecraft:sugar_cane', 0.1)
        .itemOut('minecraft:kelp', 0.1)
        .itemOut('modern_industrialization:redstone_tiny_dust', 0.01)
        .itemOut('modern_industrialization:lapis_tiny_dust', 0.01)
        .itemOut('modern_industrialization:aquarium_tiny_dust', 0.01)
        .itemOut('modern_industrialization:quartz_tiny_dust', 0.01)
        .itemOut('spectrum:topaz_powder', 0.01)
        .itemOut('spectrum:citrine_powder', 0.01)
        .itemOut('spectrum:amethyst_powder', 0.01)

    event.recipes.modern_industrialization.sifting_machine(4, 400)
        .itemIn('minecraft:red_sand')
        .itemOut('modern_industrialization:bauxite_tiny_dust', 0.02)
        .itemOut('modern_industrialization:copper_tiny_dust', 0.1)
        .itemOut('modern_industrialization:gold_tiny_dust', 0.05)

    event.recipes.modern_industrialization.sifting_machine(4, 400)
        .itemIn('minecraft:soul_sand')
        .itemOut('minecraft:nether_wart', 0.05)
        .itemOut('minecraft:netherite_scrap', 0.01)

    event.recipes.modern_industrialization.sifting_machine(4, 400)
        .itemIn('minecraft:clay')
        .itemOut('5x minecraft:clay_ball')

    event.recipes.modern_industrialization.sifting_machine(4, 400)
        .itemIn('spectrum:shale_clay')
        .itemOut('5x minecraft:clay_ball')
        .itemOut('spectrum:pyrite_chunk', 0.01)
        .itemOut('spectrum:bismuth_flake', 0.01)
        .itemOut('spectrum:moonstone_powder', 0.01)

    event.recipes.modern_industrialization.sifting_machine(4, 400)
        .itemIn('minecraft:gravel')
        .itemOut('minecraft:flint')
        .itemOut('modern_industrialization:iron_tiny_dust', 0.05)
        .itemOut('modern_industrialization:coal_tiny_dust', 0.05)
        .itemOut('modern_industrialization:copper_tiny_dust', 0.05)
        .itemOut('modern_industrialization:diamond_tiny_dust', 0.01)
        .itemOut('modern_industrialization:emerald_tiny_dust', 0.01)

    event.recipes.modern_industrialization.sifting_machine(4, 400)
        .itemIn('minecraft:dirt')
        .itemOut('expandeddelight:asparagus_seeds')
        .itemOut('minecraft:wheat_seeds', 0.25)
        .itemOut('minecraft:pumpkin_seeds', 0.25)
        .itemOut('minecraft:beetroot_seeds', 0.25)
        .itemOut('expandeddelight:chili_pepper_seeds', 0.25)
        .itemOut('farmersdelight:cabbage_seeds', 0.25)
        .itemOut('farmersdelight:tomato_seeds', 0.25)
})