
ServerEvents.recipes(event => {
    event.recipes.modern_industrialization.thermal_centrifuge(128, 600)
        .itemIn('kubejs:pure_calorite')
        .itemOut('2x modern_industrialization:calorite_hot_ingot')
        .itemOut('modern_industrialization:calorite_hot_ingot', 0.5)
        .itemOut('modern_industrialization:calorite_tiny_dust', 0.2)
        .adjacentBlock('modern_industrialization:tungsten_steel_coil', 'below')

    event.recipes.modern_industrialization.thermal_centrifuge(128, 600)
        .itemIn('kubejs:pure_iridium')
        .itemOut('2x modern_industrialization:iridium_ingot')
        .itemOut('modern_industrialization:iridium_ingot', 0.5)
        .itemOut('modern_industrialization:iridium_tiny_dust', 0.2)
        .adjacentBlock('modern_industrialization:tungsten_steel_coil', 'below')

    event.recipes.modern_industrialization.thermal_centrifuge(128, 600)
        .itemIn('kubejs:pure_terrasteel')
        .itemOut('5x botania:terrasteel_nugget')
        .itemOut('3x botania:terrasteel_nugget', 0.5)
        .adjacentBlock('modern_industrialization:tungsten_steel_coil', 'below')

    event.recipes.modern_industrialization.thermal_centrifuge(128, 600)
        .itemIn('kubejs:pure_titanium')
        .itemOut('2x modern_industrialization:titanium_hot_ingot')
        .itemOut('modern_industrialization:titanium_hot_ingot', 0.5)
        .itemOut('modern_industrialization:titanium_tiny_dust', 0.2)
        .adjacentBlock('modern_industrialization:tungsten_steel_coil', 'below')

    event.recipes.modern_industrialization.thermal_centrifuge(64, 400)
        .itemIn('kubejs:pure_uranium')
        .itemOut('2x modern_industrialization:uranium_ingot')
        .itemOut('modern_industrialization:uranium_ingot', 0.5)
        .itemOut('modern_industrialization:uranium_tiny_dust', 0.2)
        .adjacentBlock('modern_industrialization:kanthal_coil', 'below')

    event.recipes.modern_industrialization.thermal_centrifuge(64, 400)
        .itemIn('kubejs:pure_tungsten')
        .itemOut('2x modern_industrialization:tungsten_ingot')
        .itemOut('modern_industrialization:tungsten_ingot', 0.5)
        .itemOut('modern_industrialization:tungsten_tiny_dust', 0.2)
        .adjacentBlock('modern_industrialization:kanthal_coil', 'below')

    event.recipes.modern_industrialization.thermal_centrifuge(64, 400)
        .itemIn('kubejs:pure_beryllium')
        .itemOut('2x modern_industrialization:beryllium_ingot')
        .itemOut('modern_industrialization:beryllium_ingot', 0.5)
        .itemOut('modern_industrialization:emerald_tiny_dust', 0.2)
        .adjacentBlock('modern_industrialization:kanthal_coil', 'below')

    event.recipes.modern_industrialization.thermal_centrifuge(64, 400)
        .itemIn('kubejs:pure_desh')
        .itemOut('2x modern_industrialization:desh_hot_ingot')
        .itemOut('modern_industrialization:desh_hot_ingot', 0.5)
        .itemOut('modern_industrialization:desh_tiny_dust', 0.2)
        .adjacentBlock('modern_industrialization:kanthal_coil', 'below')

    event.recipes.modern_industrialization.thermal_centrifuge(64, 400)
        .itemIn('kubejs:pure_ostrum')
        .itemOut('2x modern_industrialization:ostrum_hot_ingot')
        .itemOut('modern_industrialization:ostrum_hot_ingot', 0.5)
        .itemOut('modern_industrialization:ostrum_tiny_dust', 0.2)
        .adjacentBlock('modern_industrialization:kanthal_coil', 'below')

    event.recipes.modern_industrialization.thermal_centrifuge(64, 400)
        .itemIn('kubejs:pure_chromium')
        .itemOut('2x modern_industrialization:chromium_hot_ingot')
        .itemOut('modern_industrialization:chromium_hot_ingot', 0.5)
        .itemOut('modern_industrialization:chromium_tiny_dust', 0.2)
        .adjacentBlock('modern_industrialization:kanthal_coil', 'below')

    event.recipes.modern_industrialization.thermal_centrifuge(64, 400)
        .itemIn('kubejs:pure_platinum')
        .itemOut('2x modern_industrialization:platinum_hot_ingot')
        .itemOut('modern_industrialization:platinum_hot_ingot', 0.5)
        .itemOut('modern_industrialization:platinum_tiny_dust', 0.2)
        .adjacentBlock('modern_industrialization:kanthal_coil', 'below')

    event.recipes.modern_industrialization.thermal_centrifuge(32, 200)
        .itemIn('spectrum:pure_certus_quartz')
        .itemOut('2x ae2:certus_quartz_crystal')
        .itemOut('ae2:certus_quartz_crystal', 0.5)
        .itemOut('modern_industrialization:quartz_tiny_dust', 0.2)
        .adjacentBlock('modern_industrialization:cupronickel_coil', 'below')

    event.recipes.modern_industrialization.thermal_centrifuge(32, 200)
        .itemIn('spectrum:pure_emerald')
        .itemOut('2x minecraft:emerald')
        .itemOut('minecraft:emerald', 0.5)
        .itemOut('modern_industrialization:beryllium_tiny_dust', 0.2)
        .adjacentBlock('modern_industrialization:cupronickel_coil', 'below')

    event.recipes.modern_industrialization.thermal_centrifuge(32, 200)
        .itemIn('kubejs:pure_silver')
        .itemOut('2x modern_industrialization:silver_ingot')
        .itemOut('modern_industrialization:silver_ingot', 0.5)
        .itemOut('modern_industrialization:silver_tiny_dust', 0.2)
        .adjacentBlock('modern_industrialization:cupronickel_coil', 'below')

    event.recipes.modern_industrialization.thermal_centrifuge(32, 200)
        .itemIn('spectrum:pure_diamond')
        .itemOut('2x minecraft:diamond')
        .itemOut('minecraft:diamond', 0.5)
        .itemOut('modern_industrialization:carbon_tiny_dust', 0.2)
        .adjacentBlock('modern_industrialization:cupronickel_coil', 'below')

    event.recipes.modern_industrialization.thermal_centrifuge(32, 200)
        .itemIn('kubejs:pure_tin')
        .itemOut('2x modern_industrialization:tin_ingot')
        .itemOut('modern_industrialization:tin_ingot', 0.5)
        .itemOut('modern_industrialization:tin_tiny_dust', 0.2)
        .adjacentBlock('modern_industrialization:cupronickel_coil', 'below')

    event.recipes.modern_industrialization.thermal_centrifuge(32, 200)
        .itemIn('spectrum:pure_coal')
        .itemOut('2x minecraft:coal')
        .itemOut('minecraft:coal', 0.5)
        .itemOut('modern_industrialization:carbon_tiny_dust', 0.2)
        .adjacentBlock('modern_industrialization:cupronickel_coil', 'below')

    event.recipes.modern_industrialization.thermal_centrifuge(32, 200)
        .itemIn('spectrum:pure_redstone')
        .itemOut('6x minecraft:redstone')
        .itemOut('2x minecraft:redstone', 0.5)
        .itemOut('modern_industrialization:neodymium_tiny_dust', 0.2)
        .adjacentBlock('modern_industrialization:cupronickel_coil', 'below')

    event.recipes.modern_industrialization.thermal_centrifuge(32, 200)
        .itemIn('spectrum:pure_iron')
        .itemOut('2x minecraft:iron_ingot')
        .itemOut('minecraft:iron_ingot', 0.5)
        .itemOut('modern_industrialization:iron_tiny_dust', 0.2)
        .adjacentBlock('modern_industrialization:cupronickel_coil', 'below')

    event.recipes.modern_industrialization.thermal_centrifuge(32, 200)
        .itemIn('spectrum:pure_fluix')
        .itemOut('2x ae2:fluix_crystal')
        .itemOut('ae2:fluix_crystal', 0.5)
        .itemOut('modern_industrialization:neodymium_tiny_dust', 0.2)
        .adjacentBlock('modern_industrialization:cupronickel_coil', 'below')

    event.recipes.modern_industrialization.thermal_centrifuge(32, 200)
        .itemIn('kubejs:pure_nickel')
        .itemOut('2x modern_industrialization:nickel_ingot')
        .itemOut('modern_industrialization:nickel_ingot', 0.5)
        .itemOut('modern_industrialization:nickel_tiny_dust', 0.2)
        .adjacentBlock('modern_industrialization:cupronickel_coil', 'below')

    event.recipes.modern_industrialization.thermal_centrifuge(32, 200)
        .itemIn('kubejs:pure_aluminum')
        .itemOut('2x modern_industrialization:aluminum_ingot')
        .itemOut('modern_industrialization:aluminum_ingot', 0.5)
        .itemOut('modern_industrialization:aluminum_tiny_dust', 0.2)
        .adjacentBlock('modern_industrialization:cupronickel_coil', 'below')

    event.recipes.modern_industrialization.thermal_centrifuge(32, 200)
        .itemIn('kubejs:pure_lead')
        .itemOut('2x modern_industrialization:lead_ingot')
        .itemOut('modern_industrialization:lead_ingot', 0.5)
        .itemOut('modern_industrialization:lead_tiny_dust', 0.2)
        .adjacentBlock('modern_industrialization:cupronickel_coil', 'below')

    event.recipes.modern_industrialization.thermal_centrifuge(32, 200)
        .itemIn('kubejs:pure_antimony')
        .itemOut('2x modern_industrialization:antimony_ingot')
        .itemOut('modern_industrialization:antimony_ingot', 0.5)
        .itemOut('modern_industrialization:antimony_tiny_dust', 0.2)
        .adjacentBlock('modern_industrialization:cupronickel_coil', 'below')

    event.recipes.modern_industrialization.thermal_centrifuge(32, 200)
        .itemIn('spectrum:pure_lapis')
        .itemOut('3x minecraft:lapis_lazuli')
        .itemOut('minecraft:lapis_lazuli', 0.5)
        .itemOut('modern_industrialization:aluminum_tiny_dust', 0.2)
        .adjacentBlock('modern_industrialization:cupronickel_coil', 'below')

    event.recipes.modern_industrialization.thermal_centrifuge(32, 200)
        .itemIn('spectrum:pure_quartz')
        .itemOut('4x minecraft:quartz')
        .itemOut('2x minecraft:quartz', 0.5)
        .itemOut('modern_industrialization:calcite_tiny_dust', 0.2)
        .adjacentBlock('modern_industrialization:cupronickel_coil', 'below')

    event.recipes.modern_industrialization.thermal_centrifuge(32, 200)
        .itemIn('spectrum:pure_netherite_scrap')
        .itemOut('2x minecraft:netherite_scrap')
        .itemOut('minecraft:netherite_scrap', 0.5)
        .itemOut('modern_industrialization:tungsten_tiny_dust', 0.2)
        .adjacentBlock('modern_industrialization:cupronickel_coil', 'below')

    event.recipes.modern_industrialization.thermal_centrifuge(32, 200)
        .itemIn('spectrum:pure_copper')
        .itemOut('2x minecraft:copper_ingot')
        .itemOut('minecraft:copper_ingot', 0.5)
        .itemOut('modern_industrialization:copper_tiny_dust', 0.2)
        .adjacentBlock('modern_industrialization:cupronickel_coil', 'below')

    event.recipes.modern_industrialization.thermal_centrifuge(32, 200)
        .itemIn('spectrum:pure_gold')
        .itemOut('2x minecraft:gold_ingot')
        .itemOut('minecraft:gold_ingot', 0.5)
        .itemOut('modern_industrialization:gold_tiny_dust', 0.2)
        .adjacentBlock('modern_industrialization:cupronickel_coil', 'below')

    event.recipes.modern_industrialization.thermal_centrifuge(32, 200)
        .itemIn('spectrum:pure_echo')
        .itemOut('minecraft:echo_shard')
        .itemOut('minecraft:echo_shard', 0.5)
        .adjacentBlock('modern_industrialization:cupronickel_coil', 'below')

    event.recipes.modern_industrialization.thermal_centrifuge(32, 200)
        .itemIn('spectrum:pure_glowstone')
        .itemOut('6x minecraft:glowstone_dust')
        .itemOut('2x minecraft:glowstone_dust', 0.5)
        .adjacentBlock('modern_industrialization:cupronickel_coil', 'below')

    event.recipes.modern_industrialization.thermal_centrifuge(32, 200)
        .itemIn('spectrum:pure_prismarine')
        .itemOut('2x minecraft:prismarine_crystals')
        .itemOut('minecraft:prismarine_crystals', 0.5)
        .adjacentBlock('modern_industrialization:cupronickel_coil', 'below')

    event.recipes.modern_industrialization.thermal_centrifuge(128, 200)
        .itemIn('spectrum:dragonbone_chunk')
        .itemOut('32x spectrum:bone_ash')
        .adjacentBlock('modern_industrialization:tungsten_steel_coil', 'below')

})
