ServerEvents.recipes(event => {
    event.recipes.modern_industrialization.electrolyzer(32, 1200)
        .itemIn('9x modern_industrialization:vanadinite_dust')
        .itemOut('7x modern_industrialization:lead_dust')
        .itemOut('modern_industrialization:vanadium_dust')
        .fluidOut('modern_industrialization:chlorine', 400)
        .fluidOut('modern_industrialization:oxygen', 2000)
    event.recipes.modern_industrialization.electrolyzer(32, 1200)
        .itemIn('9x modern_industrialization:brookite_dust')
        .itemOut('6x modern_industrialization:titanium_tiny_dust')
        .itemOut('modern_industrialization:tantalum_tiny_dust')
        .itemOut('modern_industrialization:niobium_tiny_dust')
        .fluidOut('modern_industrialization:oxygen', 2000,0.6)
    // Purified Naquadah Sulfuric solution
    event.recipes.modern_industrialization.electrolyzer(32, 600)
        .fluidIn('modern_industrialization:purified_naquadah_sulfuric_solution',1000)
        .itemOut('3x modern_industrialization:naquadah_tiny_dust')
        .fluidOut('modern_industrialization:sulfuric_acid',900)
})
