StartupEvents.registry("enchantment", event => {
    event.create("coins_instinct")
        .maxLevel(1)
        .veryRare()
        .fishingRod()
        .displayName("enchantment.kubejs.coins_instinct")
        .translationKey('enchantment.kubejs.coins_instinct.desc')
        .untradeable()
        .undiscoverable()
})
