
[energy]
	#Whether to consume energy when performing a scan. Will make the scanner a chargeable item.
	useEnergy = true
	#Amount of energy that can be stored in a scanner.
	#Range: > 0
	energyCapacityScanner = 40000
	#Amount of energy used by the range module per scan.
	#Range: > 0
	energyCostModuleRange = 500
	#Amount of energy used by the animal module per scan.
	#Range: > 0
	energyCostModuleAnimal = 25
	#Amount of energy used by the monster module per scan.
	#Range: > 0
	energyCostModuleMonster = 50
	#Amount of energy used by the common ore module per scan.
	#Range: > 0
	energyCostModuleOreCommon = 1000
	#Amount of energy used by the rare ore module per scan.
	#Range: > 0
	energyCostModuleOreRare = 5000
	#Amount of energy used by the block module per scan.
	#Range: > 0
	energyCostModuleBlock = 2000
	#Amount of energy used by the fluid module per scan.
	#Range: > 0
	energyCostModuleFluid = 50
	#Amount of energy used by the entity module per scan.
	#Range: > 0
	energyCostModuleEntity = 75

[general]
	#The basic scan radius without range modules. Higher values mean more computational
	#overhead and thus potentially worse performance while scanning.
	#IMPORTANT: some modules such as the block and ore scanner modules will already use
	#a reduced radius based on this value. Specifically, the ore scanners multiply this
	#value by 0.25, and the block scanner multiplies it by 0.5.
	#Range modules will boost the range by half this value.
	#Range: 16 ~ 128
	baseScanRadius = 64
	#How long the results from a scan should remain visible, in milliseconds.
	#Range: 1000 ~ 300000
	scanStayDuration = 10000

[blocks]
	#Registry names of blocks that should be ignored.
	#Blocks in this list will be excluded from the default ore list based on the forge:ores
	#tag and it will be impossible to tune the entity module to this block.
	ignoredBlocks = ["minecraft:command_block", "minecraft:redstone_wire", "spectrum:onyx_block", "spectrum:citrine_block", "spectrum:black_materia", "spectrum:preservation_controller", "spectrum:amethyst_basalt_lamp", "spectrum:chiseled_polished_basalt", "spectrum:chiseled_polished_calcite", "spectrum:tinted_preservation_glass", "spectrum:dike_gate_fountain", "spectrum:preservation_stone", "spectrum:dike_chiseled_preservation_stone", "spectrum:ethereal_platform", "spectrum:universe_spyhole", "spectrum:shimmerstone_block", "spectrum:citrine_basalt_lamp", "spectrum:preservation_glass", "spectrum:topaz_basalt_lamp", "spectrum:courier_statue", "spectrum:treasure_chest", "minecraft:repeater", "minecraft:sticky_piston", "spectrum:onyx_basalt_lamp", "minecraft:redstone_torch", "minecraft:flower_pot", "minecraft:small_amethyst_bud", "spectrum:large_topaz_bud", "spectrum:large_citrine_bud", "spectrum:onyx_cluster", "minecraft:white_candle", "minecraft:amethyst_block", "spectrum:topaz_block", "spectrum:preservation_roundel", "spectrum:powder_chiseled_preservation_stone", "spectrum:shimmering_preservation_bricks"]
	#Tag names of block tags that should be ignored.
	#Blocks matching a tag in this list will be excluded from the default ore list based on the
	#forge:ores tag and it will be impossible to tune the entity module to this block.
	ignoredBlockTags = []

[ores]
	#Registry names of blocks considered 'common ores', requiring the common ore scanner module.
	commonOreBlocks = ["minecraft:clay"]
	#Block tags of blocks considered 'common ores', requiring the common ore scanner module.
	commonOreBlockTags = ["c:redstone_ores", "c:coal_ores", "c:iron_ores", "c:quartz_ores", "c:copper_ores", "c:tin_ores"]
	#Registry names of blocks considered 'rare ores', requiring the rare ore scanner module.
	rareOreBlocks = ["minecraft:glowstone"]
	#Block tags of blocks considered 'rare ores', requiring the common ore scanner module.
	#Any block with the forge:ores tag is implicitly in this list, unless the block also
	#matches an ignored or common ore block tag, or is an ignored or common block.
	rareOreBlockTags = ["mythicmetals:aquarium_ores", "mythicmetals:palladium_ores", "mythicmetals:starrite_ores", "mythicmetals:unobtainium_ores", "mythicmetals:stormyx_ores", "mythicmetals:prometheum_ores", "mythicmetals:adamantite_ores"]

[fluids]
	#Fluid tags of fluids that should be ignored.
	ignoredFluidTags = []

