
ServerEvents.recipes(event => {
    event.recipes.modern_industrialization.blast_alloy_smelter(128, 600)
        .itemIn('12x modern_industrialization:yttrium_dust')
        .itemIn('12x modern_industrialization:annealed_copper_dust')
        .itemIn('8x modern_industrialization:neodymium_dust')
        .itemIn('4x modern_industrialization:iridium_dust')
        .itemOut('36x modern_industrialization:superconductor_hot_ingot')

    event.recipes.modern_industrialization.blast_alloy_smelter(128, 600)
        .itemIn('4x modern_industrialization:chromium_dust')
        .itemIn('24x modern_industrialization:iron_dust')
        .itemIn('4x modern_industrialization:nickel_dust')
        .itemIn('4x modern_industrialization:manganese_dust')
        .itemOut('36x modern_industrialization:stainless_steel_hot_ingot')

    event.recipes.modern_industrialization.blast_alloy_smelter(128, 600)
        .itemIn('4x modern_industrialization:chromium_dust')
        .itemIn('4x modern_industrialization:stainless_steel_dust')
        .itemIn('4x modern_industrialization:aluminum_dust')
        .itemOut('12x modern_industrialization:kanthal_hot_ingot')

    event.recipes.modern_industrialization.blast_alloy_smelter(128, 600)
        .itemIn('8x modern_industrialization:iron_dust')
        .itemIn('4x modern_industrialization:nickel_dust')
        .itemOut('12x modern_industrialization:invar_ingot')

    event.recipes.modern_industrialization.blast_alloy_smelter(128, 600)
        .itemIn('4x modern_industrialization:chromium_dust')
        .itemIn('24x modern_industrialization:iron_dust')
        .itemIn('4x modern_industrialization:molybdenum_dust')
        .itemIn('4x modern_industrialization:vanadium_dust')
        .itemOut('36x modern_industrialization:hsla_steel_hot_ingot')

    event.recipes.modern_industrialization.blast_alloy_smelter(128, 600)
        .itemIn('4x modern_industrialization:silver_dust')
        .itemIn('4x modern_industrialization:gold_dust')
        .itemOut('8x modern_industrialization:electrum_ingot')

    event.recipes.modern_industrialization.blast_alloy_smelter(128, 600)
        .itemIn('4x modern_industrialization:copper_dust')
        .itemIn('4x modern_industrialization:nickel_dust')
        .itemOut('8x modern_industrialization:cupronickel_ingot')

    event.recipes.modern_industrialization.blast_alloy_smelter(128, 600)
        .itemIn('4x modern_industrialization:tin_dust')
        .itemIn('12x modern_industrialization:copper_dust')
        .itemOut('16x modern_industrialization:bronze_ingot')

    event.recipes.modern_industrialization.blast_alloy_smelter(128, 600)
        .itemIn('4x modern_industrialization:lead_dust')
        .itemIn('4x modern_industrialization:antimony_dust')
        .itemOut('8x modern_industrialization:battery_alloy_ingot')

    event.recipes.modern_industrialization.blast_alloy_smelter(256, 600)
        .itemIn('4x modern_industrialization:steel_ingot')
        .itemIn('4x modern_industrialization:tungsten_ingot')
        .itemIn('4x modern_industrialization:manganese_dust')
        .itemOut('4x modern_industrialization:tungsten_steel_ingot')

    event.recipes.modern_industrialization.blast_alloy_smelter(256, 600)
        .itemIn('4x mythicmetals:carmot_ingot')
        .itemIn('4x mythicmetals:star_platinum')
        .itemIn('4x mythicmetals:stormyx_ingot')
        .itemIn('4x mythicmetals:unobtainium')
        .itemOut('4x mythicmetals:celestium_ingot')

    event.recipes.modern_industrialization.blast_alloy_smelter(256, 600)
        .itemIn('4x kubejs:raw_magical_steel')
        .itemIn('4x mythicmetals:adamantite_ingot')
        .itemIn('4x spectrum:bedrock_dust')
        .itemOut('4x mythicmetals:durasteel_ingot')

    event.recipes.modern_industrialization.blast_alloy_smelter(256, 600)
        .itemIn('4x spectrum:shimmerstone_gem')
        .itemIn('4x mythicmetals:carmot_ingot')
        .itemIn('4x mythicmetals:mythril_ingot')
        .itemIn('4x mythicmetals:orichalcum_ingot')
        .itemOut('4x mythicmetals:hallowed_ingot')

    event.recipes.modern_industrialization.blast_alloy_smelter(256, 600)
        .itemIn('16x #spectrum:gemstone_powders')
        .itemIn('8x mythicmetals:banglum_ingot')
        .itemIn('4x minecraft:iron_ingot')
        .itemOut('4x kubejs:raw_magical_steel')
})