ServerEvents.recipes(event => {
    event.recipes.modern_industrialization.drone_station(512, 72000)
        .itemIn('kubejs:mining_drone',0.15)
        .fluidIn('neepmeat:ethereal_fuel',256000)
        .itemOut('512x ad_astra:deepslate_ice_shard_ore')
        .itemOut('512x minecraft:deepslate_iron_ore')
        .itemOut('256x modern_industrialization:deepslate_iridium_ore')
        .itemOut('256x modern_industrialization:platinum_ore')
        .itemOut('256x modern_industrialization:deepslate_bauxite_ore')
        .itemOut('256x ad_astra:deepslate_desh_ore')
        .itemOut('192x minecraft:deepslate_redstone_ore')
        .itemOut("192x modern_industrialization:deepslate_tin_ore")
        .itemOut("192x minecraft:deepslate_diamond_ore")
        .itemOut('192x mythicmetals:deepslate_morkite_ore')
        .itemOut('128x spectrum:deepslate_moonstone_ore')
        .itemOut("128x minecraft:deepslate_lapis_ore")
        .itemOut("128x minecraft:deepslate_copper_ore")
        .itemOut("128x minecraft:deepslate_coal_ore")
        .itemOut("64x minecraft:deepslate_gold_ore")
        .itemOut('64x mythicmetals:deepslate_unobtainium_ore')
        .dimension('ad_astra:moon_orbit')
    event.recipes.modern_industrialization.drone_station(512, 72000)
        .itemIn('kubejs:mining_drone',0.15)
        .fluidIn('neepmeat:ethereal_fuel',256000)
        .itemOut('512x modern_industrialization:deepslate_iridium_ore')
        .itemOut('512x minecraft:deepslate_iron_ore')
        .itemOut('256x ad_astra:deepslate_ice_shard_ore')
        .itemOut('256x modern_industrialization:deepslate_uranium_ore')
        .itemOut('256x modern_industrialization:deepslate_bauxite_ore')
        .itemOut('256x ad_astra:deepslate_ostrum_ore')
        .itemOut('192x minecraft:deepslate_redstone_ore')
        .itemOut("192x modern_industrialization:deepslate_tin_ore")
        .itemOut("192x minecraft:deepslate_diamond_ore")
        .itemOut('192x mythicmetals:deepslate_adamantite_ore')
        .itemOut('128x spectrum:deepslate_azurite_ore')
        .itemOut("128x minecraft:deepslate_gold_ore")
        .itemOut("128x minecraft:deepslate_copper_ore")
        .itemOut("128x minecraft:deepslate_coal_ore")
        .itemOut("64x minecraft:deepslate_lapis_ore")
        .itemOut('64x mythicmetals:deepslate_prometheum_ore')
        .dimension('ad_astra:mars_orbit')
    event.recipes.modern_industrialization.drone_station(512, 72000)
        .itemIn('kubejs:mining_drone',0.15)
        .fluidIn('neepmeat:ethereal_fuel',256000)
        .itemOut('512x modern_industrialization:platinum_ore')
        .itemOut('512x minecraft:deepslate_coal_ore')
        .itemOut('256x ad_astra:deepslate_ice_shard_ore')
        .itemOut('256x modern_industrialization:deepslate_uranium_ore')
        .itemOut('256x modern_industrialization:deepslate_antimony_ore')
        .itemOut('256x ad_astra:deepslate_calorite_ore')
        .itemOut('192x minecraft:deepslate_redstone_ore')
        .itemOut("192x modern_industrialization:deepslate_tin_ore")
        .itemOut("192x minecraft:deepslate_copper_ore")
        .itemOut('192x mythicmetals:deepslate_orichalcum_ore')
        .itemOut('128x spectrum:deepslate_malachite_ore')
        .itemOut("128x minecraft:deepslate_gold_ore")
        .itemOut("128x minecraft:deepslate_diamond_ore")
        .itemOut("128x minecraft:deepslate_iron_ore")
        .itemOut("64x minecraft:deepslate_emerald_ore")
        .itemOut('64x mythicmetals:deepslate_runite_ore')
        .dimension('ad_astra:venus_orbit')
    event.recipes.modern_industrialization.drone_station(512, 72000)
        .itemIn('kubejs:mining_drone',0.15)
        .fluidIn('neepmeat:ethereal_fuel',256000)
        .itemOut('512x modern_industrialization:deepslate_tungsten_ore')
        .itemOut('512x modern_industrialization:deepslate_mozanite_ore')
        .itemOut('256x modern_industrialization:deepslate_roquesite_ore')
        .itemOut('256x modern_industrialization:deepslate_uranium_ore')
        .itemOut('256x modern_industrialization:deepslate_molybdenite_ore')
        .itemOut('256x modern_industrialization:deepslate_brookite_ore')
        .itemOut("192x modern_industrialization:deepslate_iridium_ore")
        .itemOut("192x modern_industrialization:deepslate_gadolinite_ore")
        .itemOut('192x minecraft:deepslate_redstone_ore')
        .itemOut('192x mythicmetals:deepslate_adamantite_ore')
        .itemOut('128x spectrum:deepslate_shimmerstone_ore')
        .itemOut("128x minecraft:deepslate_gold_ore")
        .itemOut("128x minecraft:deepslate_diamond_ore")
        .itemOut("128x minecraft:deepslate_iron_ore")
        .itemOut("64x minecraft:deepslate_emerald_ore")
        .itemOut('64x mythicmetals:deepslate_carmot_ore')
        .dimension('ad_astra:mercury_orbit')
    event.recipes.modern_industrialization.drone_station(512, 72000)
        .itemIn('kubejs:mining_drone',0.15)
        .fluidIn('neepmeat:ethereal_fuel',256000)
        .itemOut('512x spectrum:deepslate_azurite_ore')
        .itemOut('512x ad_astra:deepslate_ice_shard_ore')
        .itemOut('256x spectrum:deepslate_malachite_ore')
        .itemOut('256x ad_astra:deepslate_desh_ore')
        .itemOut('256x ad_astra:deepslate_ostrum_ore')
        .itemOut('256x ad_astra:deepslate_calorite_ore')
        .itemOut('192x spectrum:deepslate_onyx_ore')
        .itemOut('192x spectrum:deepslate_citrine_ore')
        .itemOut('192x spectrum:deepslate_amethyst_ore')
        .itemOut('192x spectrum:deepslate_topaz_ore')
        .itemOut('128x spectrum:deepslate_moonstone_ore')
        .itemOut('128x mythicmetals:deepslate_mythril_ore')
        .itemOut('128x mythicmetals:deepslate_morkite_ore')
        .itemOut('128x mythicmetals:deepslate_adamantite_ore')
        .itemOut('64x modern_industrialization:deepslate_iridium_ore')
        .itemOut('64x modern_industrialization:deepslate_uranium_ore')
        .dimension('ad_astra:glacio_orbit')
});
