//priority: 0

ServerEvents.recipes(event => {
    event.recipes.modern_industrialization.void_distillation_machine(256, 100)
        .fluidIn('modern_industrialization:void', 250)
        .itemOut('spectrum:pure_coal', 0.60)
        .itemOut('spectrum:pure_iron', 0.45)
        .itemOut('spectrum:pure_gold', 0.3)
        .itemOut('spectrum:pure_lapis', 0.3)
        .itemOut('spectrum:pure_quartz', 0.15)
        .itemOut('spectrum:pure_redstone', 0.3)
        .itemOut('spectrum:pure_copper', 0.45)
        .itemOut('spectrum:pure_emerald', 0.15)
        .itemOut('spectrum:pure_glowstone', 0.3)
        .itemOut('spectrum:pure_diamond', 0.15)
        .itemOut('kubejs:pure_tin', 0.25)
        .itemOut('kubejs:pure_silver', 0.1)
        .itemOut('kubejs:pure_nickel', 0.15)
        .itemOut('kubejs:pure_antimony', 0.25)

    event.recipes.modern_industrialization.void_distillation_machine(512, 100)
        .fluidIn('modern_industrialization:purified_void', 250)
        .itemOut('spectrum:pure_certus_quartz', 0.25)
        .itemOut('spectrum:pure_fluix', 0.15)
        .itemOut('spectrum:pure_netherite_scrap', 0.05)
        .itemOut('kubejs:pure_desh', 0.15)
        .itemOut('kubejs:pure_ostrum', 0.1)
        .itemOut('kubejs:pure_calorite', 0.05)
        .itemOut('kubejs:pure_lead', 0.15)
        .itemOut('kubejs:pure_iridium', 0.015)
        .itemOut('kubejs:pure_titanium', 0.1)
        .itemOut('kubejs:pure_platinum', 0.1)
        .itemOut('kubejs:pure_beryllium', 0.2)
        .itemOut('kubejs:pure_aluminum', 0.4)
        .itemOut('kubejs:pure_uranium', 0.15)
});
